In [1]:
pip install spotipy

Requirement already satisfied: spotipy in c:\users\admin\anaconda3\lib\site-packages (2.25.1)
Requirement already satisfied: redis>=3.5.3 in c:\users\admin\anaconda3\lib\site-packages (from spotipy) (6.4.0)
Requirement already satisfied: requests>=2.25.0 in c:\users\admin\anaconda3\lib\site-packages (from spotipy) (2.32.3)
Requirement already satisfied: urllib3>=1.26.0 in c:\users\admin\anaconda3\lib\site-packages (from spotipy) (2.3.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\admin\anaconda3\lib\site-packages (from requests>=2.25.0->spotipy) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\admin\anaconda3\lib\site-packages (from requests>=2.25.0->spotipy) (3.7)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\admin\anaconda3\lib\site-packages (from requests>=2.25.0->spotipy) (2025.4.26)
Note: you may need to restart the kernel to use updated packages.

In [44]:
import spotipy
from spotipy.oauth2 import SpotifyClientCredentials
import pandas as pd

In [3]:
client_credentials_manager = SpotifyClientCredentials(client_id="ac1189bfa89c4c1691c74c99bb2c247a" ,client_secret="81fa2c6b95224e6c901c585c28f9e4a8")

In [4]:
sp = spotipy.Spotify(client_credentials_manager = client_credentials_manager)

In [9]:
playlist_link = "https://open.spotify.com/playlist/6VOedaf3eNWDOVpa9Qdlvg"

In [10]:
playlist_url = playlist_link.split('/')[-1].split('?')[0]

In [14]:
data = sp.playlist_tracks(playlist_url)

In [16]:
data['items']

[{'added_at': '2025-03-07T07:49:17Z',
  'added_by': {'external_urls': {'spotify': 'https://open.spotify.com/user/31rzz7jr6t3e3mqgitwppkmfg2ve'},
   'href': 'https://api.spotify.com/v1/users/31rzz7jr6t3e3mqgitwppkmfg2ve',
   'id': '31rzz7jr6t3e3mqgitwppkmfg2ve',
   'type': 'user',
   'uri': 'spotify:user:31rzz7jr6t3e3mqgitwppkmfg2ve'},
  'is_local': False,
  'primary_color': None,
  'track': {'preview_url': None,
   'available_markets': ['AR',
    'AU',
    'AT',
    'BE',
    'BO',
    'BR',
    'BG',
    'CA',
    'CL',
    'CO',
    'CR',
    'CY',
    'CZ',
    'DK',
    'DO',
    'DE',
    'EC',
    'EE',
    'SV',
    'FI',
    'FR',
    'GR',
    'GT',
    'HN',
    'HK',
    'HU',
    'IS',
    'IE',
    'IT',
    'LV',
    'LT',
    'LU',
    'MY',
    'MT',
    'MX',
    'NL',
    'NZ',
    'NI',
    'NO',
    'PA',
    'PY',
    'PE',
    'PH',
    'PL',
    'PT',
    'SG',
    'SK',
    'ES',
    'SE',
    'CH',
    'TW',
    'TR',
    'UY',
    'US',
    'GB',
    'AD',
    'LI',
    'MC',
    'ID',
    'JP',
    'TH',
    'VN',
    'RO',
    'IL',
    'ZA',
    'SA',
    'AE',
    'BH',
    'QA',
    'OM',
    'KW',
    'EG',
    'MA',
    'DZ',
    'TN',
    'LB',
    'JO',
    'PS',
    'IN',
    'BY',
    'KZ',
    'MD',
    'UA',
    'AL',
    'BA',
    'HR',
    'ME',
    'MK',
    'RS',
    'SI',
    'KR',
    'BD',
    'PK',
    'LK',
    'GH',
    'KE',
    'NG',
    'TZ',
    'UG',
    'AG',
    'AM',
    'BS',
    'BB',
    'BZ',
    'BT',
    'BW',
    'BF',
    'CV',
    'CW',
    'DM',
    'FJ',
    'GM',
    'GE',
    'GD',
    'GW',
    'GY',
    'HT',
    'JM',
    'KI',
    'LS',
    'LR',
    'MW',
    'MV',
    'ML',
    'MH',
    'FM',
    'NA',
    'NR',
    'NE',
    'PW',
    'PG',
    'PR',
    'WS',
    'SM',
    'ST',
    'SN',
    'SC',
    'SL',
    'SB',
    'KN',
    'LC',
    'VC',
    'SR',
    'TL',
    'TO',
    'TT',
    'TV',
    'VU',
    'AZ',
    'BN',
    'BI',
    'KH',
    'CM',
    'TD',
    'KM',
    'GQ',
    'SZ',
    'GA',
    'GN',
    'KG',
    'LA',
    'MO',
    'MR',
    'MN',
    'NP',
    'RW',
    'TG',
    'UZ',
    'ZW',
    'BJ',
    'MG',
    'MU',
    'MZ',
    'AO',
    'CI',
    'DJ',
    'ZM',
    'CD',
    'CG',
    'IQ',
    'LY',
    'TJ',
    'VE',
    'ET',
    'XK'],
   'explicit': False,
   'type': 'track',
   'episode': False,
   'track': True,
   'album': {'available_markets': ['AR',
     'AU',
     'AT',
     'BE',
     'BO',
     'BR',
     'BG',
     'CA',
     'CL',
     'CO',
     'CR',
     'CY',
     'CZ',
     'DK',
     'DO',
     'DE',
     'EC',
     'EE',
     'SV',
     'FI',
     'FR',
     'GR',
     'GT',
     'HN',
     'HK',
     'HU',
     'IS',
     'IE',
     'IT',
     'LV',
     'LT',
     'LU',
     'MY',
     'MT',
     'MX',
     'NL',
     'NZ',
     'NI',
     'NO',
     'PA',
     'PY',
     'PE',
     'PH',
     'PL',
     'PT',
     'SG',
     'SK',
     'ES',
     'SE',
     'CH',
     'TW',
     'TR',
     'UY',
     'US',
     'GB',
     'AD',
     'LI',
     'MC',
     'ID',
     'JP',
     'TH',
     'VN',
     'RO',
     'IL',
     'ZA',
     'SA',
     'AE',
     'BH',
     'QA',
     'OM',
     'KW',
     'EG',
     'MA',
     'DZ',
     'TN',
     'LB',
     'JO',
     'PS',
     'IN',
     'BY',
     'KZ',
     'MD',
     'UA',
     'AL',
     'BA',
     'HR',
     'ME',
     'MK',
     'RS',
     'SI',
     'KR',
     'BD',
     'PK',
     'LK',
     'GH',
     'KE',
     'NG',
     'TZ',
     'UG',
     'AG',
     'AM',
     'BS',
     'BB',
     'BZ',
     'BT',
     'BW',
     'BF',
     'CV',
     'CW',
     'DM',
     'FJ',
     'GM',
     'GE',
     'GD',
     'GW',
     'GY',
     'HT',
     'JM',
     'KI',
     'LS',
     'LR',
     'MW',
     'MV',
     'ML',
     'MH',
     'FM',
     'NA',
     'NR',
     'NE',
     'PW',
     'PG',
     'PR',
     'WS',
     'SM',
     'ST',
     'SN',
     'SC',
     'SL',
     'SB',
     'KN',
     'LC',
     'VC',
     'SR',
     'TL',
     'TO',
     'TT',
     'TV',
     'VU',
     'AZ',
     'BN',
     'BI',
     'KH',
     'CM',
     'TD',
     'KM',
     'GQ',
     'SZ',
     'GA',
     'GN',
     'KG',
     'LA',
     'MO',
     'MR',
     'MN',
     'NP',
     'RW',
     'TG',
     'UZ',
     'ZW',
     'BJ',
     'MG',
     'MU',
     'MZ',
     'AO',
     'CI',
     'DJ',
     'ZM',
     'CD',
     'CG',
     'IQ',
     'LY',
     'TJ',
     'VE',
     'ET',
     'XK'],
    'type': 'album',
    'album_type': 'single',
    'href': 'https://api.spotify.com/v1/albums/6xUYw5goKIoyJQi9C27UBy',
    'id': '6xUYw5goKIoyJQi9C27UBy',
    'images': [{'height': 640,
      'url': 'https://i.scdn.co/image/ab67616d0000b273becceb2d3f6a694db50fcedf',
      'width': 640},
     {'height': 300,
      'url': 'https://i.scdn.co/image/ab67616d00001e02becceb2d3f6a694db50fcedf',
      'width': 300},
     {'height': 64,
      'url': 'https://i.scdn.co/image/ab67616d00004851becceb2d3f6a694db50fcedf',
      'width': 64}],
    'name': 'NUNCA MUDA?',
    'release_date': '2025-01-09',
    'release_date_precision': 'day',
    'uri': 'spotify:album:6xUYw5goKIoyJQi9C27UBy',
    'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/5dDNNq04RjKXFOADdHd6VX'},
      'href': 'https://api.spotify.com/v1/artists/5dDNNq04RjKXFOADdHd6VX',
      'id': '5dDNNq04RjKXFOADdHd6VX',
      'name': 'Scythermane',
      'type': 'artist',
      'uri': 'spotify:artist:5dDNNq04RjKXFOADdHd6VX'},
     {'external_urls': {'spotify': 'https://open.spotify.com/artist/7lAaAGxYxk2GH8cMbTEwAL'},
      'href': 'https://api.spotify.com/v1/artists/7lAaAGxYxk2GH8cMbTEwAL',
      'id': '7lAaAGxYxk2GH8cMbTEwAL',
      'name': 'NXGHT!',
      'type': 'artist',
      'uri': 'spotify:artist:7lAaAGxYxk2GH8cMbTEwAL'},
     {'external_urls': {'spotify': 'https://open.spotify.com/artist/14hsjenLEdvafsGkk2CEiF'},
      'href': 'https://api.spotify.com/v1/artists/14hsjenLEdvafsGkk2CEiF',
      'id': '14hsjenLEdvafsGkk2CEiF',
      'name': 'MC Fabinho da Osk',
      'type': 'artist',
      'uri': 'spotify:artist:14hsjenLEdvafsGkk2CEiF'}],
    'external_urls': {'spotify': 'https://open.spotify.com/album/6xUYw5goKIoyJQi9C27UBy'},
    'total_tracks': 6},
   'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/5dDNNq04RjKXFOADdHd6VX'},
     'href': 'https://api.spotify.com/v1/artists/5dDNNq04RjKXFOADdHd6VX',
     'id': '5dDNNq04RjKXFOADdHd6VX',
     'name': 'Scythermane',
     'type': 'artist',
     'uri': 'spotify:artist:5dDNNq04RjKXFOADdHd6VX'},
    {'external_urls': {'spotify': 'https://open.spotify.com/artist/7lAaAGxYxk2GH8cMbTEwAL'},
     'href': 'https://api.spotify.com/v1/artists/7lAaAGxYxk2GH8cMbTEwAL',
     'id': '7lAaAGxYxk2GH8cMbTEwAL',
     'name': 'NXGHT!',
     'type': 'artist',
     'uri': 'spotify:artist:7lAaAGxYxk2GH8cMbTEwAL'},
    {'external_urls': {'spotify': 'https://open.spotify.com/artist/14hsjenLEdvafsGkk2CEiF'},
     'href': 'https://api.spotify.com/v1/artists/14hsjenLEdvafsGkk2CEiF',
     'id': '14hsjenLEdvafsGkk2CEiF',
     'name': 'MC Fabinho da Osk',
     'type': 'artist',
     'uri': 'spotify:artist:14hsjenLEdvafsGkk2CEiF'}],
   'disc_number': 1,
   'track_number': 1,
   'duration_ms': 81500,
   'external_ids': {'isrc': 'SGW502245352'},
   'external_urls': {'spotify': 'https://open.spotify.com/track/5EIjpM1B1VsLoKvv2iwd0P'},
   'href': 'https://api.spotify.com/v1/tracks/5EIjpM1B1VsLoKvv2iwd0P',
   'id': '5EIjpM1B1VsLoKvv2iwd0P',
   'name': 'NUNCA MUDA?',
   'popularity': 76,
   'uri': 'spotify:track:5EIjpM1B1VsLoKvv2iwd0P',
   'is_local': False},
  'video_thumbnail': {'url': None}},
 {'added_at': '2025-05-10T16:34:06Z',
  'added_by': {'external_urls': {'spotify': 'https://open.spotify.com/user/31rzz7jr6t3e3mqgitwppkmfg2ve'},
   'href': 'https://api.spotify.com/v1/users/31rzz7jr6t3e3mqgitwppkmfg2ve',
   'id': '31rzz7jr6t3e3mqgitwppkmfg2ve',
   'type': 'user',
   'uri': 'spotify:user:31rzz7jr6t3e3mqgitwppkmfg2ve'},
  'is_local': False,
  'primary_color': None,
  'track': {'preview_url': None,
   'available_markets': ['AR',
    'AU',
    'AT',
    'BE',
    'BO',
    'BR',
    'BG',
    'CA',
    'CL',
    'CO',
    'CR',
    'CY',
    'CZ',
    'DK',
    'DO',
    'DE',
    'EC',
    'EE',
    'SV',
    'FI',
    'FR',
    'GR',
    'GT',
    'HN',
    'HK',
    'HU',
    'IS',
    'IE',
    'IT',
    'LV',
    'LT',
    'LU',
    'MY',
    'MT',
    'MX',
    'NL',
    'NZ',
    'NI',
    'NO',
    'PA',
    'PY',
    'PE',
    'PH',
    'PL',
    'PT',
    'SG',
    'SK',
    'ES',
    'SE',
    'CH',
    'TW',
    'TR',
    'UY',
    'US',
    'GB',
    'AD',
    'LI',
    'MC',
    'ID',
    'JP',
    'TH',
    'VN',
    'RO',
    'IL',
    'ZA',
    'SA',
    'AE',
    'BH',
    'QA',
    'OM',
    'KW',
    'EG',
    'MA',
    'DZ',
    'TN',
    'LB',
    'JO',
    'PS',
    'IN',
    'BY',
    'KZ',
    'MD',
    'UA',
    'AL',
    'BA',
    'HR',
    'ME',
    'MK',
    'RS',
    'SI',
    'KR',
    'BD',
    'PK',
    'LK',
    'GH',
    'KE',
    'NG',
    'TZ',
    'UG',
    'AG',
    'AM',
    'BS',
    'BB',
    'BZ',
    'BT',
    'BW',
    'BF',
    'CV',
    'CW',
    'DM',
    'FJ',
    'GM',
    'GE',
    'GD',
    'GW',
    'GY',
    'HT',
    'JM',
    'KI',
    'LS',
    'LR',
    'MW',
    'MV',
    'ML',
    'MH',
    'FM',
    'NA',
    'NR',
    'NE',
    'PW',
    'PG',
    'PR',
    'WS',
    'SM',
    'ST',
    'SN',
    'SC',
    'SL',
    'SB',
    'KN',
    'LC',
    'VC',
    'SR',
    'TL',
    'TO',
    'TT',
    'TV',
    'VU',
    'AZ',
    'BN',
    'BI',
    'KH',
    'CM',
    'TD',
    'KM',
    'GQ',
    'SZ',
    'GA',
    'GN',
    'KG',
    'LA',
    'MO',
    'MR',
    'MN',
    'NP',
    'RW',
    'TG',
    'UZ',
    'ZW',
    'BJ',
    'MG',
    'MU',
    'MZ',
    'AO',
    'CI',
    'DJ',
    'ZM',
    'CD',
    'CG',
    'IQ',
    'LY',
    'TJ',
    'VE',
    'ET',
    'XK'],
   'explicit': False,
   'type': 'track',
   'episode': False,
   'track': True,
   'album': {'available_markets': ['AR',
     'AU',
     'AT',
     'BE',
     'BO',
     'BR',
     'BG',
     'CA',
     'CL',
     'CO',
     'CR',
     'CY',
     'CZ',
     'DK',
     'DO',
     'DE',
     'EC',
     'EE',
     'SV',
     'FI',
     'FR',
     'GR',
     'GT',
     'HN',
     'HK',
     'HU',
     'IS',
     'IE',
     'IT',
     'LV',
     'LT',
     'LU',
     'MY',
     'MT',
     'MX',
     'NL',
     'NZ',
     'NI',
     'NO',
     'PA',
     'PY',
     'PE',
     'PH',
     'PL',
     'PT',
     'SG',
     'SK',
     'ES',
     'SE',
     'CH',
     'TW',
     'TR',
     'UY',
     'US',
     'GB',
     'AD',
     'LI',
     'MC',
     'ID',
     'JP',
     'TH',
     'VN',
     'RO',
     'IL',
     'ZA',
     'SA',
     'AE',
     'BH',
     'QA',
     'OM',
     'KW',
     'EG',
     'MA',
     'DZ',
     'TN',
     'LB',
     'JO',
     'PS',
     'IN',
     'BY',
     'KZ',
     'MD',
     'UA',
     'AL',
     'BA',
     'HR',
     'ME',
     'MK',
     'RS',
     'SI',
     'KR',
     'BD',
     'PK',
     'LK',
     'GH',
     'KE',
     'NG',
     'TZ',
     'UG',
     'AG',
     'AM',
     'BS',
     'BB',
     'BZ',
     'BT',
     'BW',
     'BF',
     'CV',
     'CW',
     'DM',
     'FJ',
     'GM',
     'GE',
     'GD',
     'GW',
     'GY',
     'HT',
     'JM',
     'KI',
     'LS',
     'LR',
     'MW',
     'MV',
     'ML',
     'MH',
     'FM',
     'NA',
     'NR',
     'NE',
     'PW',
     'PG',
     'PR',
     'WS',
     'SM',
     'ST',
     'SN',
     'SC',
     'SL',
     'SB',
     'KN',
     'LC',
     'VC',
     'SR',
     'TL',
     'TO',
     'TT',
     'TV',
     'VU',
     'AZ',
     'BN',
     'BI',
     'KH',
     'CM',
     'TD',
     'KM',
     'GQ',
     'SZ',
     'GA',
     'GN',
     'KG',
     'LA',
     'MO',
     'MR',
     'MN',
     'NP',
     'RW',
     'TG',
     'UZ',
     'ZW',
     'BJ',
     'MG',
     'MU',
     'MZ',
     'AO',
     'CI',
     'DJ',
     'ZM',
     'CD',
     'CG',
     'IQ',
     'LY',
     'TJ',
     'VE',
     'ET',
     'XK'],
    'type': 'album',
    'album_type': 'single',
    'href': 'https://api.spotify.com/v1/albums/0I7096R74VFP2xnMmp33sY',
    'id': '0I7096R74VFP2xnMmp33sY',
    'images': [{'height': 640,
      'url': 'https://i.scdn.co/image/ab67616d0000b27336385e0fad3c87e8e8f19071',
      'width': 640},
     {'height': 300,
      'url': 'https://i.scdn.co/image/ab67616d00001e0236385e0fad3c87e8e8f19071',
      'width': 300},
     {'height': 64,
      'url': 'https://i.scdn.co/image/ab67616d0000485136385e0fad3c87e8e8f19071',
      'width': 64}],
    'name': 'PASSO BEM SOLTO',
    'release_date': '2024-04-23',
    'release_date_precision': 'day',
    'uri': 'spotify:album:0I7096R74VFP2xnMmp33sY',
    'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/5SCDfg1YoEfI5gFtXqEWah'},
      'href': 'https://api.spotify.com/v1/artists/5SCDfg1YoEfI5gFtXqEWah',
      'id': '5SCDfg1YoEfI5gFtXqEWah',
      'name': 'ATLXS',
      'type': 'artist',
      'uri': 'spotify:artist:5SCDfg1YoEfI5gFtXqEWah'}],
    'external_urls': {'spotify': 'https://open.spotify.com/album/0I7096R74VFP2xnMmp33sY'},
    'total_tracks': 5},
   'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/5SCDfg1YoEfI5gFtXqEWah'},
     'href': 'https://api.spotify.com/v1/artists/5SCDfg1YoEfI5gFtXqEWah',
     'id': '5SCDfg1YoEfI5gFtXqEWah',
     'name': 'ATLXS',
     'type': 'artist',
     'uri': 'spotify:artist:5SCDfg1YoEfI5gFtXqEWah'}],
   'disc_number': 1,
   'track_number': 3,
   'duration_ms': 116072,
   'external_ids': {'isrc': 'AUMEV2448907'},
   'external_urls': {'spotify': 'https://open.spotify.com/track/4sTlQPMyoFMPdhAJvErBN3'},
   'href': 'https://api.spotify.com/v1/tracks/4sTlQPMyoFMPdhAJvErBN3',
   'id': '4sTlQPMyoFMPdhAJvErBN3',
   'name': 'PASSO BEM SOLTO - Slowed',
   'popularity': 85,
   'uri': 'spotify:track:4sTlQPMyoFMPdhAJvErBN3',
   'is_local': False},
  'video_thumbnail': {'url': None}},
 {'added_at': '2025-03-07T07:49:21Z',
  'added_by': {'external_urls': {'spotify': 'https://open.spotify.com/user/31rzz7jr6t3e3mqgitwppkmfg2ve'},
   'href': 'https://api.spotify.com/v1/users/31rzz7jr6t3e3mqgitwppkmfg2ve',
   'id': '31rzz7jr6t3e3mqgitwppkmfg2ve',
   'type': 'user',
   'uri': 'spotify:user:31rzz7jr6t3e3mqgitwppkmfg2ve'},
  'is_local': False,
  'primary_color': None,
  'track': {'preview_url': None,
   'available_markets': ['AR',
    'AU',
    'AT',
    'BE',
    'BO',
    'BR',
    'BG',
    'CA',
    'CL',
    'CO',
    'CR',
    'CY',
    'CZ',
    'DK',
    'DO',
    'DE',
    'EC',
    'EE',
    'SV',
    'FI',
    'FR',
    'GR',
    'GT',
    'HN',
    'HK',
    'HU',
    'IS',
    'IE',
    'IT',
    'LV',
    'LT',
    'LU',
    'MY',
    'MT',
    'MX',
    'NL',
    'NZ',
    'NI',
    'NO',
    'PA',
    'PY',
    'PE',
    'PH',
    'PL',
    'PT',
    'SG',
    'SK',
    'ES',
    'SE',
    'CH',
    'TW',
    'TR',
    'UY',
    'US',
    'GB',
    'AD',
    'LI',
    'MC',
    'ID',
    'JP',
    'TH',
    'VN',
    'RO',
    'IL',
    'ZA',
    'SA',
    'AE',
    'BH',
    'QA',
    'OM',
    'KW',
    'EG',
    'MA',
    'DZ',
    'TN',
    'LB',
    'JO',
    'PS',
    'IN',
    'BY',
    'KZ',
    'MD',
    'UA',
    'AL',
    'BA',
    'HR',
    'ME',
    'MK',
    'RS',
    'SI',
    'KR',
    'BD',
    'PK',
    'LK',
    'GH',
    'KE',
    'NG',
    'TZ',
    'UG',
    'AG',
    'AM',
    'BS',
    'BB',
    'BZ',
    'BT',
    'BW',
    'BF',
    'CV',
    'CW',
    'DM',
    'FJ',
    'GM',
    'GE',
    'GD',
    'GW',
    'GY',
    'HT',
    'JM',
    'KI',
    'LS',
    'LR',
    'MW',
    'MV',
    'ML',
    'MH',
    'FM',
    'NA',
    'NR',
    'NE',
    'PW',
    'PG',
    'PR',
    'WS',
    'SM',
    'ST',
    'SN',
    'SC',
    'SL',
    'SB',
    'KN',
    'LC',
    'VC',
    'SR',
    'TL',
    'TO',
    'TT',
    'TV',
    'VU',
    'AZ',
    'BN',
    'BI',
    'KH',
    'CM',
    'TD',
    'KM',
    'GQ',
    'SZ',
    'GA',
    'GN',
    'KG',
    'LA',
    'MO',
    'MR',
    'MN',
    'NP',
    'RW',
    'TG',
    'UZ',
    'ZW',
    'BJ',
    'MG',
    'MU',
    'MZ',
    'AO',
    'CI',
    'DJ',
    'ZM',
    'CD',
    'CG',
    'IQ',
    'LY',
    'TJ',
    'VE',
    'ET',
    'XK'],
   'explicit': True,
   'type': 'track',
   'episode': False,
   'track': True,
   'album': {'available_markets': ['AR',
     'AU',
     'AT',
     'BE',
     'BO',
     'BR',
     'BG',
     'CA',
     'CL',
     'CO',
     'CR',
     'CY',
     'CZ',
     'DK',
     'DO',
     'DE',
     'EC',
     'EE',
     'SV',
     'FI',
     'FR',
     'GR',
     'GT',
     'HN',
     'HK',
     'HU',
     'IS',
     'IE',
     'IT',
     'LV',
     'LT',
     'LU',
     'MY',
     'MT',
     'MX',
     'NL',
     'NZ',
     'NI',
     'NO',
     'PA',
     'PY',
     'PE',
     'PH',
     'PL',
     'PT',
     'SG',
     'SK',
     'ES',
     'SE',
     'CH',
     'TW',
     'TR',
     'UY',
     'US',
     'GB',
     'AD',
     'LI',
     'MC',
     'ID',
     'JP',
     'TH',
     'VN',
     'RO',
     'IL',
     'ZA',
     'SA',
     'AE',
     'BH',
     'QA',
     'OM',
     'KW',
     'EG',
     'MA',
     'DZ',
     'TN',
     'LB',
     'JO',
     'PS',
     'IN',
     'BY',
     'KZ',
     'MD',
     'UA',
     'AL',
     'BA',
     'HR',
     'ME',
     'MK',
     'RS',
     'SI',
     'KR',
     'BD',
     'PK',
     'LK',
     'GH',
     'KE',
     'NG',
     'TZ',
     'UG',
     'AG',
     'AM',
     'BS',
     'BB',
     'BZ',
     'BT',
     'BW',
     'BF',
     'CV',
     'CW',
     'DM',
     'FJ',
     'GM',
     'GE',
     'GD',
     'GW',
     'GY',
     'HT',
     'JM',
     'KI',
     'LS',
     'LR',
     'MW',
     'MV',
     'ML',
     'MH',
     'FM',
     'NA',
     'NR',
     'NE',
     'PW',
     'PG',
     'PR',
     'WS',
     'SM',
     'ST',
     'SN',
     'SC',
     'SL',
     'SB',
     'KN',
     'LC',
     'VC',
     'SR',
     'TL',
     'TO',
     'TT',
     'TV',
     'VU',
     'AZ',
     'BN',
     'BI',
     'KH',
     'CM',
     'TD',
     'KM',
     'GQ',
     'SZ',
     'GA',
     'GN',
     'KG',
     'LA',
     'MO',
     'MR',
     'MN',
     'NP',
     'RW',
     'TG',
     'UZ',
     'ZW',
     'BJ',
     'MG',
     'MU',
     'MZ',
     'AO',
     'CI',
     'DJ',
     'ZM',
     'CD',
     'CG',
     'IQ',
     'LY',
     'TJ',
     'VE',
     'ET',
     'XK'],
    'type': 'album',
    'album_type': 'single',
    'href': 'https://api.spotify.com/v1/albums/4s7LxMlh6RxgdMhldfMe8u',
    'id': '4s7LxMlh6RxgdMhldfMe8u',
    'images': [{'height': 640,
      'url': 'https://i.scdn.co/image/ab67616d0000b27382b73e1b62eda395d6627542',
      'width': 640},
     {'height': 300,
      'url': 'https://i.scdn.co/image/ab67616d00001e0282b73e1b62eda395d6627542',
      'width': 300},
     {'height': 64,
      'url': 'https://i.scdn.co/image/ab67616d0000485182b73e1b62eda395d6627542',
      'width': 64}],
    'name': 'Funk de Beleza',
    'release_date': '2024-10-04',
    'release_date_precision': 'day',
    'uri': 'spotify:album:4s7LxMlh6RxgdMhldfMe8u',
    'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/3g0UoyvaTaHUrfpHiRqsD1'},
      'href': 'https://api.spotify.com/v1/artists/3g0UoyvaTaHUrfpHiRqsD1',
      'id': '3g0UoyvaTaHUrfpHiRqsD1',
      'name': 'Nateki',
      'type': 'artist',
      'uri': 'spotify:artist:3g0UoyvaTaHUrfpHiRqsD1'},
     {'external_urls': {'spotify': 'https://open.spotify.com/artist/5dDNNq04RjKXFOADdHd6VX'},
      'href': 'https://api.spotify.com/v1/artists/5dDNNq04RjKXFOADdHd6VX',
      'id': '5dDNNq04RjKXFOADdHd6VX',
      'name': 'Scythermane',
      'type': 'artist',
      'uri': 'spotify:artist:5dDNNq04RjKXFOADdHd6VX'},
     {'external_urls': {'spotify': 'https://open.spotify.com/artist/10mKIVPFtg42JIvttHQrzr'},
      'href': 'https://api.spotify.com/v1/artists/10mKIVPFtg42JIvttHQrzr',
      'id': '10mKIVPFtg42JIvttHQrzr',
      'name': 'MC MAYAH',
      'type': 'artist',

In [17]:
len(data['items'])

79

In [20]:
data['items'][0]['track']['album']

{'available_markets': ['AR',
  'AU',
  'AT',
  'BE',
  'BO',
  'BR',
  'BG',
  'CA',
  'CL',
  'CO',
  'CR',
  'CY',
  'CZ',
  'DK',
  'DO',
  'DE',
  'EC',
  'EE',
  'SV',
  'FI',
  'FR',
  'GR',
  'GT',
  'HN',
  'HK',
  'HU',
  'IS',
  'IE',
  'IT',
  'LV',
  'LT',
  'LU',
  'MY',
  'MT',
  'MX',
  'NL',
  'NZ',
  'NI',
  'NO',
  'PA',
  'PY',
  'PE',
  'PH',
  'PL',
  'PT',
  'SG',
  'SK',
  'ES',
  'SE',
  'CH',
  'TW',
  'TR',
  'UY',
  'US',
  'GB',
  'AD',
  'LI',
  'MC',
  'ID',
  'JP',
  'TH',
  'VN',
  'RO',
  'IL',
  'ZA',
  'SA',
  'AE',
  'BH',
  'QA',
  'OM',
  'KW',
  'EG',
  'MA',
  'DZ',
  'TN',
  'LB',
  'JO',
  'PS',
  'IN',
  'BY',
  'KZ',
  'MD',
  'UA',
  'AL',
  'BA',
  'HR',
  'ME',
  'MK',
  'RS',
  'SI',
  'KR',
  'BD',
  'PK',
  'LK',
  'GH',
  'KE',
  'NG',
  'TZ',
  'UG',
  'AG',
  'AM',
  'BS',
  'BB',
  'BZ',
  'BT',
  'BW',
  'BF',
  'CV',
  'CW',
  'DM',
  'FJ',
  'GM',
  'GE',
  'GD',
  'GW',
  'GY',
  'HT',
  'JM',
  'KI',
  'LS',
  'LR',
  'MW',
  'MV',
  'ML',
  'MH',
  'FM',
  'NA',
  'NR',
  'NE',
  'PW',
  'PG',
  'PR',
  'WS',
  'SM',
  'ST',
  'SN',
  'SC',
  'SL',
  'SB',
  'KN',
  'LC',
  'VC',
  'SR',
  'TL',
  'TO',
  'TT',
  'TV',
  'VU',
  'AZ',
  'BN',
  'BI',
  'KH',
  'CM',
  'TD',
  'KM',
  'GQ',
  'SZ',
  'GA',
  'GN',
  'KG',
  'LA',
  'MO',
  'MR',
  'MN',
  'NP',
  'RW',
  'TG',
  'UZ',
  'ZW',
  'BJ',
  'MG',
  'MU',
  'MZ',
  'AO',
  'CI',
  'DJ',
  'ZM',
  'CD',
  'CG',
  'IQ',
  'LY',
  'TJ',
  'VE',
  'ET',
  'XK'],
 'type': 'album',
 'album_type': 'single',
 'href': 'https://api.spotify.com/v1/albums/6xUYw5goKIoyJQi9C27UBy',
 'id': '6xUYw5goKIoyJQi9C27UBy',
 'images': [{'height': 640,
   'url': 'https://i.scdn.co/image/ab67616d0000b273becceb2d3f6a694db50fcedf',
   'width': 640},
  {'height': 300,
   'url': 'https://i.scdn.co/image/ab67616d00001e02becceb2d3f6a694db50fcedf',
   'width': 300},
  {'height': 64,
   'url': 'https://i.scdn.co/image/ab67616d00004851becceb2d3f6a694db50fcedf',
   'width': 64}],
 'name': 'NUNCA MUDA?',
 'release_date': '2025-01-09',
 'release_date_precision': 'day',
 'uri': 'spotify:album:6xUYw5goKIoyJQi9C27UBy',
 'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/5dDNNq04RjKXFOADdHd6VX'},
   'href': 'https://api.spotify.com/v1/artists/5dDNNq04RjKXFOADdHd6VX',
   'id': '5dDNNq04RjKXFOADdHd6VX',
   'name': 'Scythermane',
   'type': 'artist',
   'uri': 'spotify:artist:5dDNNq04RjKXFOADdHd6VX'},
  {'external_urls': {'spotify': 'https://open.spotify.com/artist/7lAaAGxYxk2GH8cMbTEwAL'},
   'href': 'https://api.spotify.com/v1/artists/7lAaAGxYxk2GH8cMbTEwAL',
   'id': '7lAaAGxYxk2GH8cMbTEwAL',
   'name': 'NXGHT!',
   'type': 'artist',
   'uri': 'spotify:artist:7lAaAGxYxk2GH8cMbTEwAL'},
  {'external_urls': {'spotify': 'https://open.spotify.com/artist/14hsjenLEdvafsGkk2CEiF'},
   'href': 'https://api.spotify.com/v1/artists/14hsjenLEdvafsGkk2CEiF',
   'id': '14hsjenLEdvafsGkk2CEiF',
   'name': 'MC Fabinho da Osk',
   'type': 'artist',
   'uri': 'spotify:artist:14hsjenLEdvafsGkk2CEiF'}],
 'external_urls': {'spotify': 'https://open.spotify.com/album/6xUYw5goKIoyJQi9C27UBy'},
 'total_tracks': 6}

In [21]:
data['items'][0]['track']['album']['id']

'6xUYw5goKIoyJQi9C27UBy'

In [24]:
data['items'][0]['track']['album']['name']

'NUNCA MUDA?'

In [25]:
data['items'][0]['track']['album']['release_date']

'2025-01-09'

In [26]:
data['items'][0]['track']['album']['total_tracks']

6

In [27]:
data['items'][0]['track']['album']['external_urls']

{'spotify': 'https://open.spotify.com/album/6xUYw5goKIoyJQi9C27UBy'}

In [28]:
data['items'][0]['track']['album']['external_urls']['spotify']

'https://open.spotify.com/album/6xUYw5goKIoyJQi9C27UBy'

In [31]:
album_list=[]
for row in data['items']:
    album_id = row['track']['album']['id']
    album_name = row['track']['album']['name']
    album_release_date = row['track']['album']['release_date']
    album_total_tracks = row['track']['album']['total_tracks']
    album_url = row['track']['album']['external_urls']['spotify']
    album_element = {'album_id' : album_id,'name':album_name , 'release_date' :album_release_date ,'total_tracks':album_total_tracks,
    'album_url':album_url}
    album_list.append(album_element)

In [32]:
album_list

[{'album_id': '6xUYw5goKIoyJQi9C27UBy',
  'name': 'NUNCA MUDA?',
  'release_date': '2025-01-09',
  'total_tracks': 6,
  'album_url': 'https://open.spotify.com/album/6xUYw5goKIoyJQi9C27UBy'},
 {'album_id': '0I7096R74VFP2xnMmp33sY',
  'name': 'PASSO BEM SOLTO',
  'release_date': '2024-04-23',
  'total_tracks': 5,
  'album_url': 'https://open.spotify.com/album/0I7096R74VFP2xnMmp33sY'},
 {'album_id': '4s7LxMlh6RxgdMhldfMe8u',
  'name': 'Funk de Beleza',
  'release_date': '2024-10-04',
  'total_tracks': 3,
  'album_url': 'https://open.spotify.com/album/4s7LxMlh6RxgdMhldfMe8u'},
 {'album_id': '3bT53CJPMsSXSn0vDAX2Do',
  'name': 'DIA DELÍCIA',
  'release_date': '2025-04-25',
  'total_tracks': 4,
  'album_url': 'https://open.spotify.com/album/3bT53CJPMsSXSn0vDAX2Do'},
 {'album_id': '5fvUS8yHMCkTZj4sJ0FHDV',
  'name': 'Vem Vem',
  'release_date': '2025-05-30',
  'total_tracks': 4,
  'album_url': 'https://open.spotify.com/album/5fvUS8yHMCkTZj4sJ0FHDV'},
 {'album_id': '5D17Gk0J7jPXLvWMszqijF',
  'name': 'MONTAGEM TOMADA',
  'release_date': '2025-03-21',
  'total_tracks': 4,
  'album_url': 'https://open.spotify.com/album/5D17Gk0J7jPXLvWMszqijF'},
 {'album_id': '2JCCZCrAWvohxlUXRRz36I',
  'name': 'COM MEDO!',
  'release_date': '2025-03-06',
  'total_tracks': 5,
  'album_url': 'https://open.spotify.com/album/2JCCZCrAWvohxlUXRRz36I'},
 {'album_id': '3gciIH7IvN83uLz6Ay983i',
  'name': 'FUNK SIGILO',
  'release_date': '2025-03-14',
  'total_tracks': 4,
  'album_url': 'https://open.spotify.com/album/3gciIH7IvN83uLz6Ay983i'},
 {'album_id': '4ZopuwBxqYKDYkKh61tNqv',
  'name': 'MENTE MÁ',
  'release_date': '2025-05-16',
  'total_tracks': 4,
  'album_url': 'https://open.spotify.com/album/4ZopuwBxqYKDYkKh61tNqv'},
 {'album_id': '6dNugoBYWvUDQDtLurImhw',
  'name': 'X-TALI',
  'release_date': '2024-08-23',
  'total_tracks': 1,
  'album_url': 'https://open.spotify.com/album/6dNugoBYWvUDQDtLurImhw'},
 {'album_id': '1kmsUHDC0n611meNgzRkuw',
  'name': 'FUNK UNIVERSO',
  'release_date': '2024-07-03',
  'total_tracks': 4,
  'album_url': 'https://open.spotify.com/album/1kmsUHDC0n611meNgzRkuw'},
 {'album_id': '5g6rpHaTCaF9tXWfiHd2Cr',
  'name': 'MONTAGEM BATCHI',
  'release_date': '2025-04-11',
  'total_tracks': 4,
  'album_url': 'https://open.spotify.com/album/5g6rpHaTCaF9tXWfiHd2Cr'},
 {'album_id': '2VW8krMRkhGJmdlcHbyTfZ',
  'name': 'MONTAGEM BAILÃO',
  'release_date': '2025-04-04',
  'total_tracks': 5,
  'album_url': 'https://open.spotify.com/album/2VW8krMRkhGJmdlcHbyTfZ'},
 {'album_id': '0Qi6ZoqjRHB9W3yZl5Jb25',
  'name': 'Amor Na Praia',
  'release_date': '2025-03-26',
  'total_tracks': 5,
  'album_url': 'https://open.spotify.com/album/0Qi6ZoqjRHB9W3yZl5Jb25'},
 {'album_id': '3JsABNfp6sTjgcawWxzmj7',
  'name': 'MONTAGEM XONADA',
  'release_date': '2025-07-02',
  'total_tracks': 4,
  'album_url': 'https://open.spotify.com/album/3JsABNfp6sTjgcawWxzmj7'},
 {'album_id': '7CWmZcjCHJWd7detYptzAX',
  'name': 'LOS VOLTAJE',
  'release_date': '2025-04-11',
  'total_tracks': 5,
  'album_url': 'https://open.spotify.com/album/7CWmZcjCHJWd7detYptzAX'},
 {'album_id': '2acEAXK1zIr0cPBkIDDJgz',
  'name': 'LUNA BALA',
  'release_date': '2025-04-18',
  'total_tracks': 6,
  'album_url': 'https://open.spotify.com/album/2acEAXK1zIr0cPBkIDDJgz'},
 {'album_id': '62R2H85ZiKLp0lYHPprQWV',
  'name': 'MTG - RITMO ZELDA',
  'release_date': '2024-06-28',
  'total_tracks': 4,
  'album_url': 'https://open.spotify.com/album/62R2H85ZiKLp0lYHPprQWV'},
 {'album_id': '4FRxgE6LA2UGJ5yz8diaI9',
  'name': 'FUNKED UP',
  'release_date': '2024-01-19',
  'total_tracks': 3,
  'album_url': 'https://open.spotify.com/album/4FRxgE6LA2UGJ5yz8diaI9'},
 {'album_id': '6Zd0Hg3HKVH7xhBPgESQy1',
  'name': 'FUNK DO BOUNCE (Slowed)',
  'release_date': '2024-08-30',
  'total_tracks': 1,
  'album_url': 'https://open.spotify.com/album/6Zd0Hg3HKVH7xhBPgESQy1'},
 {'album_id': '1QFKbF3Oot9Ad1NnRCAG32',
  'name': 'X-SLIDE',
  'release_date': '2024-05-10',
  'total_tracks': 4,
  'album_url': 'https://open.spotify.com/album/1QFKbF3Oot9Ad1NnRCAG32'},
 {'album_id': '3tSeUNn7yOQPEex7jwS9Bf',
  'name': 'GLORY',
  'release_date': '2024-05-24',
  'total_tracks': 3,
  'album_url': 'https://open.spotify.com/album/3tSeUNn7yOQPEex7jwS9Bf'},
 {'album_id': '4QmDrxVGw99LUJOubfPJz9',
  'name': 'SPOOKY',
  'release_date': '2024-10-24',
  'total_tracks': 4,
  'album_url': 'https://open.spotify.com/album/4QmDrxVGw99LUJOubfPJz9'},
 {'album_id': '1qlnjo9SZtK01FqDyjv6nM',
  'name': 'EI DO SENSACIO!',
  'release_date': '2024-07-29',
  'total_tracks': 4,
  'album_url': 'https://open.spotify.com/album/1qlnjo9SZtK01FqDyjv6nM'},
 {'album_id': '06a7H7nusNMvM7yL8m3fy1',
  'name': 'AURA',
  'release_date': '2024-07-12',
  'total_tracks': 3,
  'album_url': 'https://open.spotify.com/album/06a7H7nusNMvM7yL8m3fy1'},
 {'album_id': '5rDznSixlUXNxJySfWQNb7',
  'name': 'REI DO BRASIL',
  'release_date': '2023-06-02',
  'total_tracks': 1,
  'album_url': 'https://open.spotify.com/album/5rDznSixlUXNxJySfWQNb7'},
 {'album_id': '1vQpZhp0nRdlUT4m2cgV4k',
  'name': 'Mexican Phonk Eki',
  'release_date': '2023-06-23',
  'total_tracks': 3,
  'album_url': 'https://open.spotify.com/album/1vQpZhp0nRdlUT4m2cgV4k'},
 {'album_id': '5n9EF7hP2GRMiklzLpPY0E',
  'name': 'AVANGARD (Slowed)',
  'release_date': '2024-08-02',
  'total_tracks': 1,
  'album_url': 'https://open.spotify.com/album/5n9EF7hP2GRMiklzLpPY0E'},
 {'album_id': '2Osz2h7ZjKHOZh5grL7o6G',
  'name': 'BAIXO',
  'release_date': '2023-09-19',
  'total_tracks': 1,
  'album_url': 'https://open.spotify.com/album/2Osz2h7ZjKHOZh5grL7o6G'},
 {'album_id': '1k9oQsBjwIhc4vF32zxvY5',
  'name': 'NEXT!',
  'release_date': '2024-06-07',
  'total_tracks': 4,
  'album_url': 'https://open.spotify.com/album/1k9oQsBjwIhc4vF32zxvY5'},
 {'album_id': '27XmqsKeLyr5jDURAordcd',
  'name': 'TUCA DONKA',
  'release_date': '2023-07-28',
  'total_tracks': 1,
  'album_url': 'https://open.spotify.com/album/27XmqsKeLyr5jDURAordcd'},
 {'album_id': '7JslfZtjZ430btdARyxLQ4',
  'name': 'PYTHON FUNK',
  'release_date': '2024-08-23',
  'total_tracks': 4,
  'album_url': 'https://open.spotify.com/album/7JslfZtjZ430btdARyxLQ4'},
 {'album_id': '6DptPhwLku8xvWBodULnC6',
  'name': 'Orquestra Maldita',
  'release_date': '2023-06-15',
  'total_tracks': 1,
  'album_url': 'https://open.spotify.com/album/6DptPhwLku8xvWBodULnC6'},
 {'album_id': '1ILssfrknV8cQv5QvwBGUY',
  'name': 'DNA',
  'release_date': '2023-12-21',
  'total_tracks': 3,
  'album_url': 'https://open.spotify.com/album/1ILssfrknV8cQv5QvwBGUY'},
 {'album_id': '6tf2ziKDZQJinItJi99wBW',
  'name': 'SPACE!',
  'release_date': '2024-04-26',
  'total_tracks': 3,
  'album_url': 'https://open.spotify.com/album/6tf2ziKDZQJinItJi99wBW'},
 {'album_id': '3BsuqyYCV0DYIBrDi1SKwQ',
  'name': 'Sequência da Dz7',
  'release_date': '2023-05-07',
  'total_tracks': 1,
  'album_url': 'https://open.spotify.com/album/3BsuqyYCV0DYIBrDi1SKwQ'},
 {'album_id': '2EuOCirl08WxbRY2cfj4H5',
  'name': 'Life in Rio',
  'release_date': '2023-03-17',
  'total_tracks': 1,
  'album_url': 'https://open.spotify.com/album/2EuOCirl08WxbRY2cfj4H5'},
 {'album_id': '3Iw0jAPzwgmuqSIWQa9i8W',
  'name': 'FUNK INFERNAL',
  'release_date': '2024-09-27',
  'total_tracks': 1,
  'album_url': 'https://open.spotify.com/album/3Iw0jAPzwgmuqSIWQa9i8W'},
 {'album_id': '1R1KJCX1oc3xqSbABo2Wpn',
  'name': 'Montagem Injuriosum Retines (Slowed)',
  'release_date': '2024-08-23',
  'total_tracks': 1,
  'album_url': 'https://open.spotify.com/album/1R1KJCX1oc3xqSbABo2Wpn'},
 {'album_id': '2bqWrlHmNh4M41xOr0p7iN',
  'name': 'Funk Secreto (Ultra Slowed)',
  'release_date': '2024-09-09',
  'total_tracks': 1,
  'album_url': 'https://open.spotify.com/album/2bqWrlHmNh4M41xOr0p7iN'},
 {'album_id': '3HEJNpi4OtYpYQlGy2anVB',
  'name': 'void',
  'release_date': '2024-08-23',
  'total_tracks': 3,
  'album_url': 'https://open.spotify.com/album/3HEJNpi4OtYpYQlGy2anVB'},
 {'album_id': '5jXbkZ8fgtvq5OufR9LJz4',
  'name': 'BLUE HORIZON FUNK',
  'release_date': '2024-11-25',
  'total_tracks': 5,
  'album_url': 'https://open.spotify.com/album/5jXbkZ8fgtvq5OufR9LJz4'},
 {'album_id': '7hNzImuUou9dBftesPXcAt',
  'name': 'BLAH',
  'release_date': '2025-02-13',
  'total_tracks': 1,
  'album_url': 'https://open.spotify.com/album/7hNzImuUou9dBftesPXcAt'},
 {'album_id': '1Idktx9vdSSkm1yxABycnf',
  'name': 'DON`T STOP',
  'release_date': '2024-04-19',
  'total_tracks': 5,
  'album_url': 'https://open.spotify.com/album/1Idktx9vdSSkm1yxABycnf'},
 {'album_id': '3xCc8FxQsm6AE7ZWJ7h5sx',
  'name': 'SLAY!',
  'release_date': '2024-03-15',
  'total_tracks': 4,
  'album_url': 'https://open.spotify.com/album/3xCc8FxQsm6AE7ZWJ7h5sx'},
 {'album_id': '5eEfzNcFaXPsBXJzkPiD3S',
  'name': 'Beeper Funk (Slowed)',
  'release_date': '2024-08-09',
  'total_tracks': 2,
  'album_url': 'https://open.spotify.com/album/5eEfzNcFaXPsBXJzkPiD3S'},
 {'album_id': '6PZBt4XZvd1ElHAHG31J1j',
  'name': 'FUNK DO BALKAN',
  'release_date': '2024-10-18',
  'total_tracks': 4,
  'album_url': 'https://open.spotify.com/album/6PZBt4XZvd1ElHAHG31J1j'},
 {'album_id': '05EQpLFKhJ1m4YElm4zDHr',
  'name': 'Ela Vira Mortal',
  'release_date': '2022-08-05',
  'total_tracks': 1,
  'album_url': 'https://open.spotify.com/album/05EQpLFKhJ1m4YElm4zDHr'},
 {'album_id': '5Ide1hRSwzUYUnTQhq6CBv',
  'name': 'Death Is No More',
  'release_date': '2021-01-25',
  'total_tracks': 1,
  'album_url': 'https://open.spotify.com/album/5Ide1hRSwzUYUnTQhq6CBv'},
 {'album_id': '7Bc7xEWvkW01bvq5jAhCQS',
  'name': 'YUM YUM',
  'release_date': '2023-06-23',
  'total_tracks': 3,
  'album_url': 'https://open.spotify.com/album/7Bc7xEWvkW01bvq5jAhCQS'},
 {'album_id': '2DNOGCn0szoh9f3rAnhF7b',
  'name': 'BAD PARENTING FUNK',
  'release_date': '2024-10-22',
  'total_tracks': 4,
  'album_url': 'https://open.spotify.com/album/2DNOGCn0szoh9f3rAnhF7b'},
 {'album_id': '4ibsk1iPM7xDpJkNXREmsl',
  'name': 'MANDA BALA',
  'release_date': '2023-12-08',
  'total_tracks': 1,
  'album_url': 'https://open.spotify.com/album/4ibsk1iPM7xDpJkNXREmsl'},
 {'album_id': '7lolzbhq4moSJPfFpdosl5',
  'name': 'RISADA CHUCK 01',
  'release_date': '2024-08-26',
  'total_tracks': 4,
  'album_url': 'https://open.spotify.com/album/7lolzbhq4moSJPfFpdosl5'},
 {'album_id': '5J00ADHG1jlJiLjQDPURVh',
  'name': 'ICEWHORE!',
  'release_date': '2023-03-24',
  'total_tracks': 1,
  'album_url': 'https://open.spotify.com/album/5J00ADHG1jlJiLjQDPURVh'},
 {'album_id': '28N1pcdMLhrEajfJKkBkl1',
  'name': 'MONTAGEM DIAMANTE ROSA',
  'release_date': '2024-01-09',
  'total_tracks': 2,
  'album_url': 'https://open.spotify.com/album/28N1pcdMLhrEajfJKkBkl1'},
 {'album_id': '7DGsEVuwdKBKrzDx8fzEKn',
  'name': 'MTG - VINGANÇA',
  'release_date': '2024-01-26',
  'total_tracks': 1,
  'album_url': 'https://open.spotify.com/album/7DGsEVuwdKBKrzDx8fzEKn'},
 {'album_id': '6h4Lw0QisEuuAwmnMQvbse',
  'name': 'VAPO NO SETOR',
  'release_date': '2024-08-13',
  'total_tracks': 5,
  'album_url': 'https://open.spotify.com/album/6h4Lw0QisEuuAwmnMQvbse'},
 {'album_id': '3D2j7JQjj9Kjc8sOfikmV6',
  'name': 'Montagem Melodia Explosiva',
  'release_date': '2024-09-06',
  'total_tracks': 4,
  'album_url': 'https://open.spotify.com/album/3D2j7JQjj9Kjc8sOfikmV6'},
 {'album_id': '43DSGSYCywacjEkdeSv4DC',
  'name': 'MASHA ULTRAFUNK',
  'release_date': '2024-03-07',
  'total_tracks': 3,
  'album_url': 'https://open.spotify.com/album/43DSGSYCywacjEkdeSv4DC'},
 {'album_id': '6dRJ8zaG9oTGrwpfu0Itld',
  'name': 'z-beta 2',
  'release_date': '2025-01-03',
  'total_tracks': 4,
  'album_url': 'https://open.spotify.com/album/6dRJ8zaG9oTGrwpfu0Itld'},
 {'album_id': '4yUHDMHDEl6Th3jPimciMz',
  'name': 'MY TYPE',
  'release_date': '2025-01-03',
  'total_tracks': 5,
  'album_url': 'https://open.spotify.com/album/4yUHDMHDEl6Th3jPimciMz'},
 {'album_id': '0yr5YRR7l813mmHITxmFWa',
  'name': 'BLOODY!',
  'release_date': '2024-08-27',
  'total_tracks': 4,
  'album_url': 'https://open.spotify.com/album/0yr5YRR7l813mmHITxmFWa'},
 {'album_id': '6OCivCvAUhsjgqn4EJXH87',
  'name': 'freedom from self',
  'release_date': '2024-09-16',
  'total_tracks': 8,
  'album_url': 'https://open.spotify.com/album/6OCivCvAUhsjgqn4EJXH87'},
 {'album_id': '572YC1K4uc7PjFqb6xaICD',
  'name': 'BOUNCE FUNK (Slowed)',
  'release_date': '2025-02-15',
  'total_tracks': 1,
  'album_url': 'https://open.spotify.com/album/572YC1K4uc7PjFqb6xaICD'},
 {'album_id': '5qaY84OJqYT635rMGeWBzJ',
  'name': 'CUTE DEPRESSED',
  'release_date': '2024-02-02',
  'total_tracks': 1,
  'album_url': 'https://open.spotify.com/album/5qaY84OJqYT635rMGeWBzJ'},
 {'album_id': '3Aw43kkDlLE5ZXwQPGHWgO',
  'name': 'MONTAGEM LADRAO',
  'release_date': '2025-02-05',
  'total_tracks': 5,
  'album_url': 'https://open.spotify.com/album/3Aw43kkDlLE5ZXwQPGHWgO'},
 {'album_id': '1fsqVvld64Nym3Byfl6ekY',
  'name': 'VOLKSWAGEN FUNK',
  'release_date': '2025-01-24',
  'total_tracks': 4,
  'album_url': 'https://open.spotify.com/album/1fsqVvld64Nym3Byfl6ekY'},
 {'album_id': '0TwAp1jAUFp1PQtdDlDDW3',
  'name': 'GHOST!',
  'release_date': '2022-12-02',
  'total_tracks': 1,
  'album_url': 'https://open.spotify.com/album/0TwAp1jAUFp1PQtdDlDDW3'},
 {'album_id': '0JQT0alFPE0pKxgiLfhwYz',
  'name': 'Montagem sombra estelar 1.0',
  'release_date': '2024-11-30',
  'total_tracks': 4,
  'album_url': 'https://open.spotify.com/album/0JQT0alFPE0pKxgiLfhwYz'},
 {'album_id': '6mjnYcgnUPMXZpadY3ctr1',
  'name': 'Scopin',
  'release_date': '2022-04-08',
  'total_tracks': 1,
  'album_url': 'https://open.spotify.com/album/6mjnYcgnUPMXZpadY3ctr1'},
 {'album_id': '1l8if9zQ8F0MEHVWYrMREe',
  'name': 'Montagem Mysterious Game',
  'release_date': '2023-12-01',
  'total_tracks': 3,
  'album_url': 'https://open.spotify.com/album/1l8if9zQ8F0MEHVWYrMREe'},
 {'album_id': '6s28IiIJ7ElbJfTPn03D6Y',
  'name': 'THOMAS',
  'release_date': '2024-04-12',
  'total_tracks': 1,
  'album_url': 'https://open.spotify.com/album/6s28IiIJ7ElbJfTPn03D6Y'},
 {'album_id': '4F2WvpcBhSzlbn3WIITz2B',
  'name': 'MAZKO',
  'release_date': '2024-10-25',
  'total_tracks': 3,
  'album_url': 'https://open.spotify.com/album/4F2WvpcBhSzlbn3WIITz2B'},
 {'album_id': '0Qi6ZoqjRHB9W3yZl5Jb25',
  'name': 'Amor Na Praia',
  'release_date': '2025-03-26',
  'total_tracks': 5,
  'album_url': 'https://open.spotify.com/album/0Qi6ZoqjRHB9W3yZl5Jb25'},
 {'album_id': '5YHGz0NvgBlhKefmyhP9zO',
  'name': 'Automotivo Bibi Fogosa',
  'release_date': '2023-11-10',
  'total_tracks': 1,
  'album_url': 'https://open.spotify.com/album/5YHGz0NvgBlhKefmyhP9zO'},
 {'album_id': '4KfNJxpu5wfMuGktR9l9LB',
  'name': 'CANTO DE LUNA',
  'release_date': '2025-05-16',
  'total_tracks': 5,
  'album_url': 'https://open.spotify.com/album/4KfNJxpu5wfMuGktR9l9LB'},
 {'album_id': '6L63sOxoncxwRrf2ktyudM',
  'name': 'OLHA MENSAGEM',
  'release_date': '2025-04-16',
  'total_tracks': 6,
  'album_url': 'https://open.spotify.com/album/6L63sOxoncxwRrf2ktyudM'},
 {'album_id': '5k8jDV518pIk74gBsU72fi',
  'name': 'MONTAGEM COMA',
  'release_date': '2025-06-06',
  'total_tracks': 4,
  'album_url': 'https://open.spotify.com/album/5k8jDV518pIk74gBsU72fi'},
 {'album_id': '17Q5BWWS8c59puiKKg2fRO',
  'name': 'JOGO MORTO',
  'release_date': '2024-11-08',
  'total_tracks': 4,
  'album_url': 'https://open.spotify.com/album/17Q5BWWS8c59puiKKg2fRO'}]

In [38]:
artists_list =[]
for row in data['items']:
    for key,value in row.items():
        if key == 'track':
            for artist in value['artists']:
                artist_dict ={'artists_id':artist['id'], 'artists_name':artist['name'], 'external_url':artist['href']}
                artists_list.append(artist_dict)

In [39]:
artists_list

[{'artists_id': '5dDNNq04RjKXFOADdHd6VX',
  'artists_name': 'Scythermane',
  'external_url': 'https://api.spotify.com/v1/artists/5dDNNq04RjKXFOADdHd6VX'},
 {'artists_id': '7lAaAGxYxk2GH8cMbTEwAL',
  'artists_name': 'NXGHT!',
  'external_url': 'https://api.spotify.com/v1/artists/7lAaAGxYxk2GH8cMbTEwAL'},
 {'artists_id': '14hsjenLEdvafsGkk2CEiF',
  'artists_name': 'MC Fabinho da Osk',
  'external_url': 'https://api.spotify.com/v1/artists/14hsjenLEdvafsGkk2CEiF'},
 {'artists_id': '5SCDfg1YoEfI5gFtXqEWah',
  'artists_name': 'ATLXS',
  'external_url': 'https://api.spotify.com/v1/artists/5SCDfg1YoEfI5gFtXqEWah'},
 {'artists_id': '3g0UoyvaTaHUrfpHiRqsD1',
  'artists_name': 'Nateki',
  'external_url': 'https://api.spotify.com/v1/artists/3g0UoyvaTaHUrfpHiRqsD1'},
 {'artists_id': '5dDNNq04RjKXFOADdHd6VX',
  'artists_name': 'Scythermane',
  'external_url': 'https://api.spotify.com/v1/artists/5dDNNq04RjKXFOADdHd6VX'},
 {'artists_id': '10mKIVPFtg42JIvttHQrzr',
  'artists_name': 'MC MAYAH',
  'external_url': 'https://api.spotify.com/v1/artists/10mKIVPFtg42JIvttHQrzr'},
 {'artists_id': '1kd6WqngBvP0Vthu1sGI0j',
  'artists_name': 'Nakama',
  'external_url': 'https://api.spotify.com/v1/artists/1kd6WqngBvP0Vthu1sGI0j'},
 {'artists_id': '2Q3xviVw2VXFRXtsF2gpR1',
  'artists_name': 'ΣP',
  'external_url': 'https://api.spotify.com/v1/artists/2Q3xviVw2VXFRXtsF2gpR1'},
 {'artists_id': '2q5vFLZus8uaVSzmIwH4Tz',
  'artists_name': 'Jmilton',
  'external_url': 'https://api.spotify.com/v1/artists/2q5vFLZus8uaVSzmIwH4Tz'},
 {'artists_id': '67PBOFpTBFaNkhz5IouBwi',
  'artists_name': 'MC Xangai',
  'external_url': 'https://api.spotify.com/v1/artists/67PBOFpTBFaNkhz5IouBwi'},
 {'artists_id': '7kk9ucvRJim0NMM89Lml2Y',
  'artists_name': 'MXZI',
  'external_url': 'https://api.spotify.com/v1/artists/7kk9ucvRJim0NMM89Lml2Y'},
 {'artists_id': '6s4LSwgbzTAfnN6OUfegJB',
  'artists_name': 'Sayfalse',
  'external_url': 'https://api.spotify.com/v1/artists/6s4LSwgbzTAfnN6OUfegJB'},
 {'artists_id': '5dDNNq04RjKXFOADdHd6VX',
  'artists_name': 'Scythermane',
  'external_url': 'https://api.spotify.com/v1/artists/5dDNNq04RjKXFOADdHd6VX'},
 {'artists_id': '0exQbKNFd9pLmdIGycwmlf',
  'artists_name': 'h6itam',
  'external_url': 'https://api.spotify.com/v1/artists/0exQbKNFd9pLmdIGycwmlf'},
 {'artists_id': '1kd6WqngBvP0Vthu1sGI0j',
  'artists_name': 'Nakama',
  'external_url': 'https://api.spotify.com/v1/artists/1kd6WqngBvP0Vthu1sGI0j'},
 {'artists_id': '3awueWqdp1OZudPelsEIgx',
  'artists_name': 'Mc Staff',
  'external_url': 'https://api.spotify.com/v1/artists/3awueWqdp1OZudPelsEIgx'},
 {'artists_id': '7qIgmxSjoXEeifSVDh8nIt',
  'artists_name': 'MXCCREE',
  'external_url': 'https://api.spotify.com/v1/artists/7qIgmxSjoXEeifSVDh8nIt'},
 {'artists_id': '1dX1zejt24Ojiu0lX4T1ZM',
  'artists_name': 'DJ GL3CHEKY',
  'external_url': 'https://api.spotify.com/v1/artists/1dX1zejt24Ojiu0lX4T1ZM'},
 {'artists_id': '0Vxqvpm9tpZcz6d4egDtjX',
  'artists_name': 'MC PR',
  'external_url': 'https://api.spotify.com/v1/artists/0Vxqvpm9tpZcz6d4egDtjX'},
 {'artists_id': '2vKxv2oKVSEJZ1VmuLUOvY',
  'artists_name': 'Irokz',
  'external_url': 'https://api.spotify.com/v1/artists/2vKxv2oKVSEJZ1VmuLUOvY'},
 {'artists_id': '7kk9ucvRJim0NMM89Lml2Y',
  'artists_name': 'MXZI',
  'external_url': 'https://api.spotify.com/v1/artists/7kk9ucvRJim0NMM89Lml2Y'},
 {'artists_id': '55TpSGABb9xsmXHkqbv3ti',
  'artists_name': 'Rushex',
  'external_url': 'https://api.spotify.com/v1/artists/55TpSGABb9xsmXHkqbv3ti'},
 {'artists_id': '6gzkhdNfpMIPg91TnzlcCh',
  'artists_name': 'MONTAGEM',
  'external_url': 'https://api.spotify.com/v1/artists/6gzkhdNfpMIPg91TnzlcCh'},
 {'artists_id': '0jrirfCZkRU3iA2sH9JEko',
  'artists_name': 'Repsaj',
  'external_url': 'https://api.spotify.com/v1/artists/0jrirfCZkRU3iA2sH9JEko'},
 {'artists_id': '7kk9ucvRJim0NMM89Lml2Y',
  'artists_name': 'MXZI',
  'external_url': 'https://api.spotify.com/v1/artists/7kk9ucvRJim0NMM89Lml2Y'},
 {'artists_id': '5SCDfg1YoEfI5gFtXqEWah',
  'artists_name': 'ATLXS',
  'external_url': 'https://api.spotify.com/v1/artists/5SCDfg1YoEfI5gFtXqEWah'},
 {'artists_id': '34giN3qeTOdgDSJIdtIMdm',
  'artists_name': 'Mc Jhey',
  'external_url': 'https://api.spotify.com/v1/artists/34giN3qeTOdgDSJIdtIMdm'},
 {'artists_id': '5bePP411ITzZyWf1QZ2SX4',
  'artists_name': 'Flame Runner',
  'external_url': 'https://api.spotify.com/v1/artists/5bePP411ITzZyWf1QZ2SX4'},
 {'artists_id': '7kk9ucvRJim0NMM89Lml2Y',
  'artists_name': 'MXZI',
  'external_url': 'https://api.spotify.com/v1/artists/7kk9ucvRJim0NMM89Lml2Y'},
 {'artists_id': '6U0dJxYVB41L8WDZ02Nwuk',
  'artists_name': 'Dj Samir',
  'external_url': 'https://api.spotify.com/v1/artists/6U0dJxYVB41L8WDZ02Nwuk'},
 {'artists_id': '0JGZRsRtFTQ0ZVBq9b2ZEj',
  'artists_name': 'DJ Javi26',
  'external_url': 'https://api.spotify.com/v1/artists/0JGZRsRtFTQ0ZVBq9b2ZEj'},
 {'artists_id': '6s4LSwgbzTAfnN6OUfegJB',
  'artists_name': 'Sayfalse',
  'external_url': 'https://api.spotify.com/v1/artists/6s4LSwgbzTAfnN6OUfegJB'},
 {'artists_id': '02wf6SCDwrs2qTX09X0IRE',
  'artists_name': "Yb Wasg'ood",
  'external_url': 'https://api.spotify.com/v1/artists/02wf6SCDwrs2qTX09X0IRE'},
 {'artists_id': '09cKncAQn28NqTUORLMwSR',
  'artists_name': 'Ariis',
  'external_url': 'https://api.spotify.com/v1/artists/09cKncAQn28NqTUORLMwSR'},
 {'artists_id': '02wf6SCDwrs2qTX09X0IRE',
  'artists_name': "Yb Wasg'ood",
  'external_url': 'https://api.spotify.com/v1/artists/02wf6SCDwrs2qTX09X0IRE'},
 {'artists_id': '09cKncAQn28NqTUORLMwSR',
  'artists_name': 'Ariis',
  'external_url': 'https://api.spotify.com/v1/artists/09cKncAQn28NqTUORLMwSR'},
 {'artists_id': '2nGwC9QG6Hpw4fSDgNpn5n',
  'artists_name': 'JXM',
  'external_url': 'https://api.spotify.com/v1/artists/2nGwC9QG6Hpw4fSDgNpn5n'},
 {'artists_id': '4DWPOsGWbW7sBHb1UuBvWs',
  'artists_name': 'Polaris',
  'external_url': 'https://api.spotify.com/v1/artists/4DWPOsGWbW7sBHb1UuBvWs'},
 {'artists_id': '4nl0CCx6PpEOOr2Z2ThPdp',
  'artists_name': 'xxanteria',
  'external_url': 'https://api.spotify.com/v1/artists/4nl0CCx6PpEOOr2Z2ThPdp'},
 {'artists_id': '6JjQbtAO09K7qBEW2pdX5s',
  'artists_name': 'isq',
  'external_url': 'https://api.spotify.com/v1/artists/6JjQbtAO09K7qBEW2pdX5s'},
 {'artists_id': '09cKncAQn28NqTUORLMwSR',
  'artists_name': 'Ariis',
  'external_url': 'https://api.spotify.com/v1/artists/09cKncAQn28NqTUORLMwSR'},
 {'artists_id': '2vPnS0IpayC2RVFuQA08R4',
  'artists_name': '2KE',
  'external_url': 'https://api.spotify.com/v1/artists/2vPnS0IpayC2RVFuQA08R4'},
 {'artists_id': '4jM6R2LK78dVTqHVUoA4li',
  'artists_name': '808iuli',
  'external_url': 'https://api.spotify.com/v1/artists/4jM6R2LK78dVTqHVUoA4li'},
 {'artists_id': '1Sdc6ySbIvzO0X9vbyHzWm',
  'artists_name': 'Ogryzek',
  'external_url': 'https://api.spotify.com/v1/artists/1Sdc6ySbIvzO0X9vbyHzWm'},
 {'artists_id': '5tvPbCrx8LMaL9Zby5e7c2',
  'artists_name': 'fennecxx',
  'external_url': 'https://api.spotify.com/v1/artists/5tvPbCrx8LMaL9Zby5e7c2'},
 {'artists_id': '7FqHcUwnhxJZAgS3I6GFFL',
  'artists_name': 'DJ ALEX',
  'external_url': 'https://api.spotify.com/v1/artists/7FqHcUwnhxJZAgS3I6GFFL'},
 {'artists_id': '0oGN0s7dqyWbR41yMsNs0R',
  'artists_name': 'princce',
  'external_url': 'https://api.spotify.com/v1/artists/0oGN0s7dqyWbR41yMsNs0R'},
 {'artists_id': '2YXKTfoEjKVzCNI0J6rHbQ',
  'artists_name': 'FR3ST',
  'external_url': 'https://api.spotify.com/v1/artists/2YXKTfoEjKVzCNI0J6rHbQ'},
 {'artists_id': '1Sdc6ySbIvzO0X9vbyHzWm',
  'artists_name': 'Ogryzek',
  'external_url': 'https://api.spotify.com/v1/artists/1Sdc6ySbIvzO0X9vbyHzWm'},
 {'artists_id': '3qycxIGAHj1KyoAQ6PGCO6',
  'artists_name': 'Seek',
  'external_url': 'https://api.spotify.com/v1/artists/3qycxIGAHj1KyoAQ6PGCO6'},
 {'artists_id': '1nccv1GNVkBdvsYi2FB5FB',
  'artists_name': 'NUEKI',
  'external_url': 'https://api.spotify.com/v1/artists/1nccv1GNVkBdvsYi2FB5FB'},
 {'artists_id': '23P2mSsBpPkfR9fTrOc1a4',
  'artists_name': 'TOLCHONOV',
  'external_url': 'https://api.spotify.com/v1/artists/23P2mSsBpPkfR9fTrOc1a4'},
 {'artists_id': '700c9Qz2z6HZKTumeliKAw',
  'artists_name': 'LONOWN',
  'external_url': 'https://api.spotify.com/v1/artists/700c9Qz2z6HZKTumeliKAw'},
 {'artists_id': '4nl0CCx6PpEOOr2Z2ThPdp',
  'artists_name': 'xxanteria',
  'external_url': 'https://api.spotify.com/v1/artists/4nl0CCx6PpEOOr2Z2ThPdp'},
 {'artists_id': '6BWtcMF39LT5Db5FT54YYG',
  'artists_name': 'NCTS',
  'external_url': 'https://api.spotify.com/v1/artists/6BWtcMF39LT5Db5FT54YYG'},
 {'artists_id': '6rzNFUmaEVnYb8kzh9tBTt',
  'artists_name': 'CURSEDEVIL',
  'external_url': 'https://api.spotify.com/v1/artists/6rzNFUmaEVnYb8kzh9tBTt'},
 {'artists_id': '3QMpCp3GHiHXgnX1LldXWe',
  'artists_name': 'DJ FKU',
  'external_url': 'https://api.spotify.com/v1/artists/3QMpCp3GHiHXgnX1LldXWe'},
 {'artists_id': '3voCipmmrW5uF4EMA6aSbj',
  'artists_name': 'Skorde',
  'external_url': 'https://api.spotify.com/v1/artists/3voCipmmrW5uF4EMA6aSbj'},
 {'artists_id': '6s4LSwgbzTAfnN6OUfegJB',
  'artists_name': 'Sayfalse',
  'external_url': 'https://api.spotify.com/v1/artists/6s4LSwgbzTAfnN6OUfegJB'},
 {'artists_id': '62D4KEvQMmmK88mTkkWx6Q',
  'artists_name': 'RD12',
  'external_url': 'https://api.spotify.com/v1/artists/62D4KEvQMmmK88mTkkWx6Q'},
 {'artists_id': '3rt96VXGtEgD4uSOJ6B69H',
  'artists_name': 'TRASHXRL',
  'external_url': 'https://api.spotify.com/v1/artists/3rt96VXGtEgD4uSOJ6B69H'},
 {'artists_id': '3l4fsEzoeabsET7ddv0lZW',
  'artists_name': 'Mc Delux',
  'external_url': 'https://api.spotify.com/v1/artists/3l4fsEzoeabsET7ddv0lZW'},
 {'artists_id': '5IpS1TN1Crp8Ym4zjiIrtK',
  'artists_name': 'LXNGVX',
  'external_url': 'https://api.spotify.com/v1/artists/5IpS1TN1Crp8Ym4zjiIrtK'},
 {'artists_id': '6kLsCQ1gKvJmjmC8XbfqFE',
  'artists_name': 'VISXGE',
  'external_url': 'https://api.spotify.com/v1/artists/6kLsCQ1gKvJmjmC8XbfqFE'},
 {'artists_id': '5AviPhK4XqgGjtTa0m9aQc',
  'artists_name': 'NAOMI',
  'external_url': 'https://api.spotify.com/v1/artists/5AviPhK4XqgGjtTa0m9aQc'},
 {'artists_id': '3rt96VXGtEgD4uSOJ6B69H',
  'artists_name': 'TRASHXRL',
  'external_url': 'https://api.spotify.com/v1/artists/3rt96VXGtEgD4uSOJ6B69H'},
 {'artists_id': '0ivrHNM8urVaCkgRX8rtKH',
  'artists_name': 'Mc Menor Do Alvorada',
  'external_url': 'https://api.spotify.com/v1/artists/0ivrHNM8urVaCkgRX8rtKH'},
 {'artists_id': '65FHTCI8EmW94W0TdWb8ja',
  'artists_name': 'Slowboy',
  'external_url': 'https://api.spotify.com/v1/artists/65FHTCI8EmW94W0TdWb8ja'},
 {'artists_id': '1nccv1GNVkBdvsYi2FB5FB',
  'artists_name': 'NUEKI',
  'external_url': 'https://api.spotify.com/v1/artists/1nccv1GNVkBdvsYi2FB5FB'},
 {'artists_id': '6QwlKB1hO357wh5oNuuInl',
  'artists_name': 'Crazy Mano',
  'external_url': 'https://api.spotify.com/v1/artists/6QwlKB1hO357wh5oNuuInl'},
 {'artists_id': '23P2mSsBpPkfR9fTrOc1a4',
  'artists_name': 'TOLCHONOV',
  'external_url': 'https://api.spotify.com/v1/artists/23P2mSsBpPkfR9fTrOc1a4'},
 {'artists_id': '6ZhleMHIGIpjkBHrQDl4G7',
  'artists_name': 'DYGO',
  'external_url': 'https://api.spotify.com/v1/artists/6ZhleMHIGIpjkBHrQDl4G7'},
 {'artists_id': '1KoTNs0Ev2KGs7AF5lWlx3',
  'artists_name': 'Mxng0',
  'external_url': 'https://api.spotify.com/v1/artists/1KoTNs0Ev2KGs7AF5lWlx3'},
 {'artists_id': '07MaeHw0cyfmgQ9D9I61UT',
  'artists_name': 'DJ JEEAN 011',
  'external_url': 'https://api.spotify.com/v1/artists/07MaeHw0cyfmgQ9D9I61UT'},
 {'artists_id': '7vfisrjZ6AMRo5vNVLP3qQ',
  'artists_name': 'MC BM OFICIAL',
  'external_url': 'https://api.spotify.com/v1/artists/7vfisrjZ6AMRo5vNVLP3qQ'},
 {'artists_id': '0exQbKNFd9pLmdIGycwmlf',
  'artists_name': 'h6itam',
  'external_url': 'https://api.spotify.com/v1/artists/0exQbKNFd9pLmdIGycwmlf'},
 {'artists_id': '4o5PswOvXGSq0y5BqZTR9n',
  'artists_name': 'STRAWANGLE',
  'external_url': 'https://api.spotify.com/v1/artists/4o5PswOvXGSq0y5BqZTR9n'},
 {'artists_id': '2JrpgVMFW3Hpe1CwLaAORl',
  'artists_name': 'MC RP VK',
  'external_url': 'https://api.spotify.com/v1/artists/2JrpgVMFW3Hpe1CwLaAORl'},
 {'artists_id': '2ge1WtiBqengw0nAnq94Zo',
  'artists_name': 'MC Da 12',
  'external_url': 'https://api.spotify.com/v1/artists/2ge1WtiBqengw0nAnq94Zo'},
 {'artists_id': '6JjQbtAO09K7qBEW2pdX5s',
  'artists_name': 'isq',
  'external_url': 'https://api.spotify.com/v1/artists/6JjQbtAO09K7qBEW2pdX5s'},
 {'artists_id': '7lAaAGxYxk2GH8cMbTEwAL',
  'artists_name': 'NXGHT!',
  'external_url': 'https://api.spotify.com/v1/artists/7lAaAGxYxk2GH8cMbTEwAL'},
 {'artists_id': '3wQNcarvRuzhz2Fg1pVDxZ',
  'artists_name': 'DJ ANXVAR',
  'external_url': 'https://api.spotify.com/v1/artists/3wQNcarvRuzhz2Fg1pVDxZ'},
 {'artists_id': '1HJglK87YzctjxETSJqh64',
  'artists_name': 'DJ ZAP',
  'external_url': 'https://api.spotify.com/v1/artists/1HJglK87YzctjxETSJqh64'},
 {'artists_id': '4H61c3XQu4PswXGtB0MJ6N',
  'artists_name': 'Hexora',
  'external_url': 'https://api.spotify.com/v1/artists/4H61c3XQu4PswXGtB0MJ6N'},
 {'artists_id': '6WCBS0WuEBBtdV7TZMtCnh',
  'artists_name': 'Artox',
  'external_url': 'https://api.spotify.com/v1/artists/6WCBS0WuEBBtdV7TZMtCnh'},
 {'artists_id': '4epIlGy9RGEMdrfSXS2HEc',
  'artists_name': 'Alert',
  'external_url': 'https://api.spotify.com/v1/artists/4epIlGy9RGEMdrfSXS2HEc'},
 {'artists_id': '5Vd9shhZpzTYaaZ6KQNnjU',
  'artists_name': 'GLXXMSTRIDER',
  'external_url': 'https://api.spotify.com/v1/artists/5Vd9shhZpzTYaaZ6KQNnjU'},
 {'artists_id': '3Xd2WSaNywx5gn1pgRPFjF',
  'artists_name': 'Eternxlkz',
  'external_url': 'https://api.spotify.com/v1/artists/3Xd2WSaNywx5gn1pgRPFjF'},
 {'artists_id': '648ZoUpTM6iIMTCgo3lLCE',
  'artists_name': 'DJ Paulinho Mondi Da Baixa Baviera',
  'external_url': 'https://api.spotify.com/v1/artists/648ZoUpTM6iIMTCgo3lLCE'},
 {'artists_id': '0sjGfRBmq6lKmUNgt8Ptic',
  'artists_name': 'Mc Vitorioso',
  'external_url': 'https://api.spotify.com/v1/artists/0sjGfRBmq6lKmUNgt8Ptic'},
 {'artists_id': '60vF1fLR6yzLxCQUlnAYYj',
  'artists_name': '$werve',
  'external_url': 'https://api.spotify.com/v1/artists/60vF1fLR6yzLxCQUlnAYYj'},
 {'artists_id': '5UKXrvmyouEgmvon7DwwzA',
  'artists_name': 'FXRCE',
  'external_url': 'https://api.spotify.com/v1/artists/5UKXrvmyouEgmvon7DwwzA'},
 {'artists_id': '7dUNKhz7HdxExteqcREGLi',
  'artists_name': 'Mc Denny',
  'external_url': 'https://api.spotify.com/v1/artists/7dUNKhz7HdxExteqcREGLi'},
 {'artists_id': '1yTrrABG9Vr2Y9lbHupN3f',
  'artists_name': 'DJ Vilão DS',
  'external_url': 'https://api.spotify.com/v1/artists/1yTrrABG9Vr2Y9lbHupN3f'},
 {'artists_id': '4kEtpjbEnSh4WNeLF1IeG7',
  'artists_name': 'MC Zudo Boladão',
  'external_url': 'https://api.spotify.com/v1/artists/4kEtpjbEnSh4WNeLF1IeG7'},
 {'artists_id': '3LfT6BvsnMomxucwVAXGiF',
  'artists_name': 'DJ Magrin Da DZ7',
  'external_url': 'https://api.spotify.com/v1/artists/3LfT6BvsnMomxucwVAXGiF'},
 {'artists_id': '2dZI1nDPMCgcymfUeLIObc',
  'artists_name': 'MC PH77',
  'external_url': 'https://api.spotify.com/v1/artists/2dZI1nDPMCgcymfUeLIObc'},
 {'artists_id': '4RsEAdLhbUy7j3zHWauPwF',
  'artists_name': 'BLESSED MANE',
  'external_url': 'https://api.spotify.com/v1/artists/4RsEAdLhbUy7j3zHWauPwF'},
 {'artists_id': '5IpS1TN1Crp8Ym4zjiIrtK',
  'artists_name': 'LXNGVX',
  'external_url': 'https://api.spotify.com/v1/artists/5IpS1TN1Crp8Ym4zjiIrtK'},
 {'artists_id': '0f1IECbrVV952unZkzrsg2',
  'artists_name': 'Mc Gw',
  'external_url': 'https://api.spotify.com/v1/artists/0f1IECbrVV952unZkzrsg2'},
 {'artists_id': '1iKfUld50BOVBIgHy3GlGt',
  'artists_name': 'DJ CEREJASS',
  'external_url': 'https://api.spotify.com/v1/artists/1iKfUld50BOVBIgHy3GlGt'},
 {'artists_id': '6s4LSwgbzTAfnN6OUfegJB',
  'artists_name': 'Sayfalse',
  'external_url': 'https://api.spotify.com/v1/artists/6s4LSwgbzTAfnN6OUfegJB'},
 {'artists_id': '09cKncAQn28NqTUORLMwSR',
  'artists_name': 'Ariis',
  'external_url': 'https://api.spotify.com/v1/artists/09cKncAQn28NqTUORLMwSR'},
 {'artists_id': '3uA4unR7LBOcqjpbOeCs0Y',
  'artists_name': '-Prey',
  'external_url': 'https://api.spotify.com/v1/artists/3uA4unR7LBOcqjpbOeCs0Y'},
 {'artists_id': '1TTHC3GlNDaE5eVoC3BVxm',
  'artists_name': 'Lumi Athena',
  'external_url': 'https://api.spotify.com/v1/artists/1TTHC3GlNDaE5eVoC3BVxm'},
 {'artists_id': '3yn6fs9MkW1i4V3S2G8Dxs',
  'artists_name': 'vtze archive',
  'external_url': 'https://api.spotify.com/v1/artists/3yn6fs9MkW1i4V3S2G8Dxs'},
 {'artists_id': '2RqjTHL40djgpNGG2LS9O0',
  'artists_name': 'Mc Ster',
  'external_url': 'https://api.spotify.com/v1/artists/2RqjTHL40djgpNGG2LS9O0'},
 {'artists_id': '3QMpCp3GHiHXgnX1LldXWe',
  'artists_name': 'DJ FKU',
  'external_url': 'https://api.spotify.com/v1/artists/3QMpCp3GHiHXgnX1LldXWe'},
 {'artists_id': '3wQNcarvRuzhz2Fg1pVDxZ',
  'artists_name': 'DJ ANXVAR',
  'external_url': 'https://api.spotify.com/v1/artists/3wQNcarvRuzhz2Fg1pVDxZ'},
 {'artists_id': '1nzIoHG5B7klgAPdwjqRDj',
  'artists_name': 'MC LONE',
  'external_url': 'https://api.spotify.com/v1/artists/1nzIoHG5B7klgAPdwjqRDj'},
 {'artists_id': '1PvcWjADPMezv8CTyJO9Uk',
  'artists_name': 'Vermillion',
  'external_url': 'https://api.spotify.com/v1/artists/1PvcWjADPMezv8CTyJO9Uk'},
 {'artists_id': '4cM6xcafBAbS9bOa8kAjRj',
  'artists_name': 'ICEDMANE',
  'external_url': 'https://api.spotify.com/v1/artists/4cM6xcafBAbS9bOa8kAjRj'},
 {'artists_id': '1pFLuMBwabtFITLNJlEZ9z',
  'artists_name': 'DYSMANE',
  'external_url': 'https://api.spotify.com/v1/artists/1pFLuMBwabtFITLNJlEZ9z'},
 {'artists_id': '3AbeBDqk7IsG1JZEWVVcpY',
  'artists_name': 'Mc Dido',
  'external_url': 'https://api.spotify.com/v1/artists/3AbeBDqk7IsG1JZEWVVcpY'},
 {'artists_id': '5Z56BMrvQB2rBAa5kffTPD',
  'artists_name': 'HISTED',
  'external_url': 'https://api.spotify.com/v1/artists/5Z56BMrvQB2rBAa5kffTPD'},
 {'artists_id': '4Rd0aHKGS9BdLYSXVvFjv5',
  'artists_name': 'TXVSTERPLAYA',
  'external_url': 'https://api.spotify.com/v1/artists/4Rd0aHKGS9BdLYSXVvFjv5'},
 {'artists_id': '32Pxa55IN0QAmFtzWcT2w9',
  'artists_name': 'qaraqshy',
  'external_url': 'https://api.spotify.com/v1/artists/32Pxa55IN0QAmFtzWcT2w9'},
 {'artists_id': '1nzIoHG5B7klgAPdwjqRDj',
  'artists_name': 'MC LONE',
  'external_url': 'https://api.spotify.com/v1/artists/1nzIoHG5B7klgAPdwjqRDj'},
 {'artists_id': '4pmKpROq7rAVibM7qR9h6P',
  'artists_name': 'DJ ZBK',
  'external_url': 'https://api.spotify.com/v1/artists/4pmKpROq7rAVibM7qR9h6P'},
 {'artists_id': '62D4KEvQMmmK88mTkkWx6Q',
  'artists_name': 'RD12',
  'external_url': 'https://api.spotify.com/v1/artists/62D4KEvQMmmK88mTkkWx6Q'},
 {'artists_id': '1qaCszXlFNPEnCELYBixa5',
  'artists_name': 'M4GN',
  'external_url': 'https://api.spotify.com/v1/artists/1qaCszXlFNPEnCELYBixa5'},
 {'artists_id': '2ZuUKw4Pfvj7zIKxYY3HAh',
  'artists_name': 'DJ Oliver Mendes',
  'external_url': 'https://api.spotify.com/v1/artists/2ZuUKw4Pfvj7zIKxYY3HAh'},
 {'artists_id': '6T9oTkBolkKzQJ5ltR7Yr8',
  'artists_name': 'ptasinski',
  'external_url': 'https://api.spotify.com/v1/artists/6T9oTkBolkKzQJ5ltR7Yr8'},
 {'artists_id': '3BTY807ipaaT6QHW1tHTt0',
  'artists_name': 'RJ Pasin',
  'external_url': 'https://api.spotify.com/v1/artists/3BTY807ipaaT6QHW1tHTt0'},
 {'artists_id': '0pSdNszQKrzI6m9okVVSL5',
  'artists_name': 'SAPFIR',
  'external_url': 'https://api.spotify.com/v1/artists/0pSdNszQKrzI6m9okVVSL5'},
 {'artists_id': '12Swjg82MNiUOfl1GB3XFx',
  'artists_name': 'Dyan Dxddy',
  'external_url': 'https://api.spotify.com/v1/artists/12Swjg82MNiUOfl1GB3XFx'},
 {'artists_id': '5SCDfg1YoEfI5gFtXqEWah',
  'artists_name': 'ATLXS',
  'external_url': 'https://api.spotify.com/v1/artists/5SCDfg1YoEfI5gFtXqEWah'},
 {'artists_id': '7kk9ucvRJim0NMM89Lml2Y',
  'artists_name': 'MXZI',
  'external_url': 'https://api.spotify.com/v1/artists/7kk9ucvRJim0NMM89Lml2Y'},
 {'artists_id': '6guLZyE3by1cVU1ydAAKpJ',
  'artists_name': 'Itamar Mc',
  'external_url': 'https://api.spotify.com/v1/artists/6guLZyE3by1cVU1ydAAKpJ'},
 {'artists_id': '3wuzmgnvjw5FzJiz8wjrq1',
  'artists_name': 'NVRXMARV',
  'external_url': 'https://api.spotify.com/v1/artists/3wuzmgnvjw5FzJiz8wjrq1'},
 {'artists_id': '1eERcEkPBnNCbqoZHvoM2C',
  'artists_name': 'LXSTURY',

In [ ]:
song_list = []
for row in data['items']:
    song_id = row['track']['id']
    song_name = row['track']['name']
    song_duration = row['track']['duration_ms']
    song_url = row['track']['external_urls']['spotify']
    song_popularity = row['track']['popularity']
    song_added = row['added_at']
    album_id = row['track']['album']['id']
    artist_id = row['track']['album']['artists'][0]['id']
    song_element = {'song_id':song_id,'song_name':song_name,'duration_ms':song_duration,'url':song_url,
                    'popularity':song_popularity,'song_added':song_added,'album_id':album_id,
                    'artist_id':artist_id
                   }
    song_list.append(song_element)

In [42]:
song_list

[{'song_id': '5EIjpM1B1VsLoKvv2iwd0P',
  'song_name': 'NUNCA MUDA?',
  'duration_ms': 81500,
  'url': 'https://open.spotify.com/track/5EIjpM1B1VsLoKvv2iwd0P',
  'popularity': 76,
  'song_added': '2025-03-07T07:49:17Z',
  'album_id': '6xUYw5goKIoyJQi9C27UBy',
  'artist_id': '5dDNNq04RjKXFOADdHd6VX'},
 {'song_id': '4sTlQPMyoFMPdhAJvErBN3',
  'song_name': 'PASSO BEM SOLTO - Slowed',
  'duration_ms': 116072,
  'url': 'https://open.spotify.com/track/4sTlQPMyoFMPdhAJvErBN3',
  'popularity': 85,
  'song_added': '2025-05-10T16:34:06Z',
  'album_id': '0I7096R74VFP2xnMmp33sY',
  'artist_id': '5SCDfg1YoEfI5gFtXqEWah'},
 {'song_id': '43jExF2HeZ6cJIGrWF0ie4',
  'song_name': 'Funk de Beleza - Slowed',
  'duration_ms': 145115,
  'url': 'https://open.spotify.com/track/43jExF2HeZ6cJIGrWF0ie4',
  'popularity': 77,
  'song_added': '2025-03-07T07:49:21Z',
  'album_id': '4s7LxMlh6RxgdMhldfMe8u',
  'artist_id': '3g0UoyvaTaHUrfpHiRqsD1'},
 {'song_id': '094IjHeVUviN4aBnSXYsuj',
  'song_name': 'DIA DELÍCIA',
  'duration_ms': 75461,
  'url': 'https://open.spotify.com/track/094IjHeVUviN4aBnSXYsuj',
  'popularity': 86,
  'song_added': '2025-07-09T07:59:30Z',
  'album_id': '3bT53CJPMsSXSn0vDAX2Do',
  'artist_id': '1kd6WqngBvP0Vthu1sGI0j'},
 {'song_id': '2FnkrCrbXJuebXxnVtXiHI',
  'song_name': 'Vem Vem',
  'duration_ms': 83183,
  'url': 'https://open.spotify.com/track/2FnkrCrbXJuebXxnVtXiHI',
  'popularity': 83,
  'song_added': '2025-07-28T18:37:14Z',
  'album_id': '5fvUS8yHMCkTZj4sJ0FHDV',
  'artist_id': '2q5vFLZus8uaVSzmIwH4Tz'},
 {'song_id': '1mfvWzF39LwVpAm8g0LhQT',
  'song_name': 'MONTAGEM TOMADA - Slowed',
  'duration_ms': 84901,
  'url': 'https://open.spotify.com/track/1mfvWzF39LwVpAm8g0LhQT',
  'popularity': 22,
  'song_added': '2025-04-10T07:43:26Z',
  'album_id': '5D17Gk0J7jPXLvWMszqijF',
  'artist_id': '7kk9ucvRJim0NMM89Lml2Y'},
 {'song_id': '1jkqC2F17O5BugrmUj9KvO',
  'song_name': 'COM MEDO!',
  'duration_ms': 69736,
  'url': 'https://open.spotify.com/track/1jkqC2F17O5BugrmUj9KvO',
  'popularity': 74,
  'song_added': '2025-05-28T04:06:12Z',
  'album_id': '2JCCZCrAWvohxlUXRRz36I',
  'artist_id': '6s4LSwgbzTAfnN6OUfegJB'},
 {'song_id': '4kyDzE3UwJLoT3iImSh9Tj',
  'song_name': 'FUNK SIGILO - ULTRA SLOWED',
  'duration_ms': 138116,
  'url': 'https://open.spotify.com/track/4kyDzE3UwJLoT3iImSh9Tj',
  'popularity': 77,
  'song_added': '2025-07-28T18:37:53Z',
  'album_id': '3gciIH7IvN83uLz6Ay983i',
  'artist_id': '0exQbKNFd9pLmdIGycwmlf'},
 {'song_id': '11gZL0HigsqfzjTHOpdFjE',
  'song_name': 'MENTE MÁ',
  'duration_ms': 75302,
  'url': 'https://open.spotify.com/track/11gZL0HigsqfzjTHOpdFjE',
  'popularity': 85,
  'song_added': '2025-07-28T18:37:06Z',
  'album_id': '4ZopuwBxqYKDYkKh61tNqv',
  'artist_id': '1kd6WqngBvP0Vthu1sGI0j'},
 {'song_id': '6yIkBXij6NSjmRGRpQupqO',
  'song_name': 'X-TALI',
  'duration_ms': 72352,
  'url': 'https://open.spotify.com/track/6yIkBXij6NSjmRGRpQupqO',
  'popularity': 68,
  'song_added': '2025-03-07T07:52:21Z',
  'album_id': '6dNugoBYWvUDQDtLurImhw',
  'artist_id': '7qIgmxSjoXEeifSVDh8nIt'},
 {'song_id': '466x7CJlVwiFdNTLvIXwZl',
  'song_name': 'FUNK UNIVERSO',
  'duration_ms': 127500,
  'url': 'https://open.spotify.com/track/466x7CJlVwiFdNTLvIXwZl',
  'popularity': 73,
  'song_added': '2025-03-07T07:49:36Z',
  'album_id': '1kmsUHDC0n611meNgzRkuw',
  'artist_id': '2vKxv2oKVSEJZ1VmuLUOvY'},
 {'song_id': '3x22qcYuGehBV6X0K6HIoO',
  'song_name': 'MONTAGEM BATCHI',
  'duration_ms': 79151,
  'url': 'https://open.spotify.com/track/3x22qcYuGehBV6X0K6HIoO',
  'popularity': 77,
  'song_added': '2025-07-28T18:36:09Z',
  'album_id': '5g6rpHaTCaF9tXWfiHd2Cr',
  'artist_id': '7kk9ucvRJim0NMM89Lml2Y'},
 {'song_id': '1RnPdd7EKKhKN3E4o4DRsh',
  'song_name': 'MONTAGEM BAILÃO',
  'duration_ms': 103727,
  'url': 'https://open.spotify.com/track/1RnPdd7EKKhKN3E4o4DRsh',
  'popularity': 82,
  'song_added': '2025-05-29T00:41:34Z',
  'album_id': '2VW8krMRkhGJmdlcHbyTfZ',
  'artist_id': '0jrirfCZkRU3iA2sH9JEko'},
 {'song_id': '6v0sTzF8VSr3gKVxrSAoBr',
  'song_name': 'Amor Na Praia',
  'duration_ms': 88557,
  'url': 'https://open.spotify.com/track/6v0sTzF8VSr3gKVxrSAoBr',
  'popularity': 75,
  'song_added': '2025-07-09T07:59:09Z',
  'album_id': '0Qi6ZoqjRHB9W3yZl5Jb25',
  'artist_id': '5bePP411ITzZyWf1QZ2SX4'},
 {'song_id': '2Gs0iF27my40p0dANv2rAg',
  'song_name': 'MONTAGEM XONADA',
  'duration_ms': 75682,
  'url': 'https://open.spotify.com/track/2Gs0iF27my40p0dANv2rAg',
  'popularity': 88,
  'song_added': '2025-07-28T18:36:45Z',
  'album_id': '3JsABNfp6sTjgcawWxzmj7',
  'artist_id': '7kk9ucvRJim0NMM89Lml2Y'},
 {'song_id': '4LkkRLP8pldQer1YRrHwkx',
  'song_name': 'LOS VOLTAJE',
  'duration_ms': 99285,
  'url': 'https://open.spotify.com/track/4LkkRLP8pldQer1YRrHwkx',
  'popularity': 82,
  'song_added': '2025-05-29T00:36:33Z',
  'album_id': '7CWmZcjCHJWd7detYptzAX',
  'artist_id': '6s4LSwgbzTAfnN6OUfegJB'},
 {'song_id': '49t3uvN9hUNefdvtaD6HBj',
  'song_name': 'LUNA BALA - Slowed',
  'duration_ms': 124110,
  'url': 'https://open.spotify.com/track/49t3uvN9hUNefdvtaD6HBj',
  'popularity': 84,
  'song_added': '2025-05-22T21:19:11Z',
  'album_id': '2acEAXK1zIr0cPBkIDDJgz',
  'artist_id': '02wf6SCDwrs2qTX09X0IRE'},
 {'song_id': '5XwNsUvJxk38263zeXrfXI',
  'song_name': 'MTG - RITMO ZELDA - Super Slowed',
  'duration_ms': 107093,
  'url': 'https://open.spotify.com/track/5XwNsUvJxk38263zeXrfXI',
  'popularity': 16,
  'song_added': '2025-03-20T11:10:50Z',
  'album_id': '62R2H85ZiKLp0lYHPprQWV',
  'artist_id': '2nGwC9QG6Hpw4fSDgNpn5n'},
 {'song_id': '4VL5XwfATZuAVTW471Wpro',
  'song_name': 'FUNKED UP - SLOWED',
  'duration_ms': 115348,
  'url': 'https://open.spotify.com/track/4VL5XwfATZuAVTW471Wpro',
  'popularity': 72,
  'song_added': '2025-03-07T08:19:08Z',
  'album_id': '4FRxgE6LA2UGJ5yz8diaI9',
  'artist_id': '4nl0CCx6PpEOOr2Z2ThPdp'},
 {'song_id': '7IBqHkoP94VrgYKVns4eNz',
  'song_name': 'FUNK DO BOUNCE (Slowed)',
  'duration_ms': 107539,
  'url': 'https://open.spotify.com/track/7IBqHkoP94VrgYKVns4eNz',
  'popularity': 78,
  'song_added': '2025-03-07T07:49:29Z',
  'album_id': '6Zd0Hg3HKVH7xhBPgESQy1',
  'artist_id': '09cKncAQn28NqTUORLMwSR'},
 {'song_id': '60AVJqYgyAlCckC6Nh2tgO',
  'song_name': 'X-SLIDE',
  'duration_ms': 79452,
  'url': 'https://open.spotify.com/track/60AVJqYgyAlCckC6Nh2tgO',
  'popularity': 72,
  'song_added': '2025-03-07T07:51:56Z',
  'album_id': '1QFKbF3Oot9Ad1NnRCAG32',
  'artist_id': '2vPnS0IpayC2RVFuQA08R4'},
 {'song_id': '2YZ7CJV3Q1OGh7ZL9PYWcP',
  'song_name': 'GLORY',
  'duration_ms': 149522,
  'url': 'https://open.spotify.com/track/2YZ7CJV3Q1OGh7ZL9PYWcP',
  'popularity': 78,
  'song_added': '2025-03-07T07:47:52Z',
  'album_id': '3tSeUNn7yOQPEex7jwS9Bf',
  'artist_id': '1Sdc6ySbIvzO0X9vbyHzWm'},
 {'song_id': '4aT2W9wchQKAimxVFSRIva',
  'song_name': 'SPOOKY',
  'duration_ms': 96923,
  'url': 'https://open.spotify.com/track/4aT2W9wchQKAimxVFSRIva',
  'popularity': 76,
  'song_added': '2025-03-07T07:52:00Z',
  'album_id': '4QmDrxVGw99LUJOubfPJz9',
  'artist_id': '5tvPbCrx8LMaL9Zby5e7c2'},
 {'song_id': '2vbl2mqgwZCPqiYjn3MPhS',
  'song_name': 'EI DO SENSACIO!',
  'duration_ms': 101089,
  'url': 'https://open.spotify.com/track/2vbl2mqgwZCPqiYjn3MPhS',
  'popularity': 64,
  'song_added': '2025-03-07T07:52:14Z',
  'album_id': '1qlnjo9SZtK01FqDyjv6nM',
  'artist_id': '0oGN0s7dqyWbR41yMsNs0R'},
 {'song_id': '2TNv2GxMpIO8AyPiD7TLxj',
  'song_name': 'AURA',
  'duration_ms': 115906,
  'url': 'https://open.spotify.com/track/2TNv2GxMpIO8AyPiD7TLxj',
  'popularity': 74,
  'song_added': '2025-03-07T07:47:46Z',
  'album_id': '06a7H7nusNMvM7yL8m3fy1',
  'artist_id': '1Sdc6ySbIvzO0X9vbyHzWm'},
 {'song_id': '6Seth37t5I69wFbuGFrsiG',
  'song_name': 'REI DO BRASIL',
  'duration_ms': 97846,
  'url': 'https://open.spotify.com/track/6Seth37t5I69wFbuGFrsiG',
  'popularity': 58,
  'song_added': '2025-03-07T07:54:42Z',
  'album_id': '5rDznSixlUXNxJySfWQNb7',
  'artist_id': '3qycxIGAHj1KyoAQ6PGCO6'},
 {'song_id': '586x98q1tY2vlDlhN1BwQM',
  'song_name': 'Mexican Phonk Eki',
  'duration_ms': 98067,
  'url': 'https://open.spotify.com/track/586x98q1tY2vlDlhN1BwQM',
  'popularity': 61,
  'song_added': '2025-03-07T07:54:56Z',
  'album_id': '1vQpZhp0nRdlUT4m2cgV4k',
  'artist_id': '1nccv1GNVkBdvsYi2FB5FB'},
 {'song_id': '1EPi3TSB6vGbGQ4IHVpxco',
  'song_name': 'AVANGARD - Slowed',
  'duration_ms': 199450,
  'url': 'https://open.spotify.com/track/1EPi3TSB6vGbGQ4IHVpxco',
  'popularity': 73,
  'song_added': '2025-03-07T07:57:42Z',
  'album_id': '5n9EF7hP2GRMiklzLpPY0E',
  'artist_id': '700c9Qz2z6HZKTumeliKAw'},
 {'song_id': '0RVmg31gzlshCm356g0HF2',
  'song_name': 'BAIXO',
  'duration_ms': 104013,
  'url': 'https://open.spotify.com/track/0RVmg31gzlshCm356g0HF2',
  'popularity': 63,
  'song_added': '2025-03-07T07:59:54Z',
  'album_id': '2Osz2h7ZjKHOZh5grL7o6G',
  'artist_id': '4nl0CCx6PpEOOr2Z2ThPdp'},
 {'song_id': '5hL2t5WyC9bibNDVkhVvDx',
  'song_name': 'NEXT!',
  'duration_ms': 99692,
  'url': 'https://open.spotify.com/track/5hL2t5WyC9bibNDVkhVvDx',
  'popularity': 76,
  'song_added': '2025-03-07T08:02:31Z',
  'album_id': '1k9oQsBjwIhc4vF32zxvY5',
  'artist_id': '6BWtcMF39LT5Db5FT54YYG'},
 {'song_id': '7bxyNLXYaEYaZTxAuQTHlD',
  'song_name': 'TUCA DONKA',
  'duration_ms': 75692,
  'url': 'https://open.spotify.com/track/7bxyNLXYaEYaZTxAuQTHlD',
  'popularity': 69,
  'song_added': '2025-03-07T08:02:58Z',
  'album_id': '27XmqsKeLyr5jDURAordcd',
  'artist_id': '6rzNFUmaEVnYb8kzh9tBTt'},
 {'song_id': '4YvxfQF9QCXykqi2ahREC4',
  'song_name': 'PYTHON FUNK',
  'duration_ms': 74285,
  'url': 'https://open.spotify.com/track/4YvxfQF9QCXykqi2ahREC4',
  'popularity': 65,
  'song_added': '2025-03-07T07:59:49Z',
  'album_id': '7JslfZtjZ430btdARyxLQ4',
  'artist_id': '6s4LSwgbzTAfnN6OUfegJB'},
 {'song_id': '7hcagAQDiI0TgUOv337NIr',
  'song_name': 'Orquestra Maldita',
  'duration_ms': 119777,
  'url': 'https://open.spotify.com/track/7hcagAQDiI0TgUOv337NIr',
  'popularity': 67,
  'song_added': '2025-03-07T08:03:02Z',
  'album_id': '6DptPhwLku8xvWBodULnC6',
  'artist_id': '3rt96VXGtEgD4uSOJ6B69H'},
 {'song_id': '3i6tlvYU1BSAM3yGQNemtM',
  'song_name': 'DNA',
  'duration_ms': 88740,
  'url': 'https://open.spotify.com/track/3i6tlvYU1BSAM3yGQNemtM',
  'popularity': 69,
  'song_added': '2025-03-07T08:03:06Z',
  'album_id': '1ILssfrknV8cQv5QvwBGUY',
  'artist_id': '5IpS1TN1Crp8Ym4zjiIrtK'},
 {'song_id': '38dHd7r4mSSVhRvVulD1na',
  'song_name': 'SPACE! - Super Slowed',
  'duration_ms': 109848,
  'url': 'https://open.spotify.com/track/38dHd7r4mSSVhRvVulD1na',
  'popularity': 72,
  'song_added': '2025-03-07T08:03:13Z',
  'album_id': '6tf2ziKDZQJinItJi99wBW',
  'artist_id': '5AviPhK4XqgGjtTa0m9aQc'},
 {'song_id': '0hEjvk5rMwLzt9rUcFmZG7',
  'song_name': 'Sequência da Dz7',
  'duration_ms': 119231,
  'url': 'https://open.spotify.com/track/0hEjvk5rMwLzt9rUcFmZG7',
  'popularity': 67,
  'song_added': '2025-03-07T08:03:17Z',
  'album_id': '3BsuqyYCV0DYIBrDi1SKwQ',
  'artist_id': '3rt96VXGtEgD4uSOJ6B69H'},
 {'song_id': '7vtGOauV0Zz8Px5EJYm7d7',
  'song_name': 'Life in Rio',
  'duration_ms': 94418,
  'url': 'https://open.spotify.com/track/7vtGOauV0Zz8Px5EJYm7d7',
  'popularity': 62,
  'song_added': '2025-03-07T08:03:21Z',
  'album_id': '2EuOCirl08WxbRY2cfj4H5',
  'artist_id': '65FHTCI8EmW94W0TdWb8ja'},
 {'song_id': '56BZSVROHDzuiYM8C2Zv3y',
  'song_name': 'FUNK INFERNAL',
  'duration_ms': 90000,
  'url': 'https://open.spotify.com/track/56BZSVROHDzuiYM8C2Zv3y',
  'popularity': 74,
  'song_added': '2025-03-07T08:07:21Z',
  'album_id': '3Iw0jAPzwgmuqSIWQa9i8W',
  'artist_id': '6ZhleMHIGIpjkBHrQDl4G7'},
 {'song_id': '1T09ARjY1LkuSJVJTk100T',
  'song_name': 'Montagem Injuriosum Retines - Slowed',
  'duration_ms': 151632,
  'url': 'https://open.spotify.com/track/1T09ARjY1LkuSJVJTk100T',
  'popularity': 51,
  'song_added': '2025-03-07T08:07:49Z',
  'album_id': '1R1KJCX1oc3xqSbABo2Wpn',
  'artist_id': '07MaeHw0cyfmgQ9D9I61UT'},
 {'song_id': '1XBarxRIZkpNzIqj2IlIMe',
  'song_name': 'Funk Secreto - Ultra Slowed',
  'duration_ms': 89773,
  'url': 'https://open.spotify.com/track/1XBarxRIZkpNzIqj2IlIMe',
  'popularity': 60,
  'song_added': '2025-03-07T08:08:01Z',
  'album_id': '2bqWrlHmNh4M41xOr0p7iN',
  'artist_id': '2JrpgVMFW3Hpe1CwLaAORl'},
 {'song_id': '4Pxm8GR4lQT1WnhvN2qNvx',
  'song_name': 'void - super slowed',
  'duration_ms': 101420,
  'url': 'https://open.spotify.com/track/4Pxm8GR4lQT1WnhvN2qNvx',
  'popularity': 70,
  'song_added': '2025-03-07T08:08:06Z',
  'album_id': '3HEJNpi4OtYpYQlGy2anVB',
  'artist_id': '6JjQbtAO09K7qBEW2pdX5s'},
 {'song_id': '6ISgjQNYq70ahUOL9rOrcz',
  'song_name': 'BLUE HORIZON FUNK - SLOWED',
  'duration_ms': 85642,
  'url': 'https://open.spotify.com/track/6ISgjQNYq70ahUOL9rOrcz',
  'popularity': 67,
  'song_added': '2025-03-07T08:08:14Z',
  'album_id': '5jXbkZ8fgtvq5OufR9LJz4',
  'artist_id': '7lAaAGxYxk2GH8cMbTEwAL'},
 {'song_id': '5kfzt2xCxOCrmt1H6H2d8O',
  'song_name': 'BLAH',
  'duration_ms': 141641,
  'url': 'https://open.spotify.com/track/5kfzt2xCxOCrmt1H6H2d8O',
  'popularity': 0,
  'song_added': '2025-03-07T08:08:19Z',
  'album_id': '7hNzImuUou9dBftesPXcAt',
  'artist_id': '4H61c3XQu4PswXGtB0MJ6N'},
 {'song_id': '52uQ2fQqo9hX5H4p7Niq0b',
  'song_name': 'DON`T STOP - Slowed',
  'duration_ms': 179904,
  'url': 'https://open.spotify.com/track/52uQ2fQqo9hX5H4p7Niq0b',
  'popularity': 71,
  'song_added': '2025-03-07T08:18:37Z',
  'album_id': '1Idktx9vdSSkm1yxABycnf',
  'artist_id': '5Vd9shhZpzTYaaZ6KQNnjU'},
 {'song_id': '67smGwuPEtA6GAfeweAVNO',
  'song_name': 'SLAY!',
  'duration_ms': 107076,
  'url': 'https://open.spotify.com/track/67smGwuPEtA6GAfeweAVNO',
  'popularity': 76,
  'song_added': '2025-03-07T08:18:44Z',
  'album_id': '3xCc8FxQsm6AE7ZWJ7h5sx',
  'artist_id': '3Xd2WSaNywx5gn1pgRPFjF'},
 {'song_id': '02WKo37gebkkQKor2TCuTk',
  'song_name': 'Beeper Funk - Slowed',
  'duration_ms': 103375,
  'url': 'https://open.spotify.com/track/02WKo37gebkkQKor2TCuTk',
  'popularity': 66,
  'song_added': '2025-03-07T08:19:20Z',
  'album_id': '5eEfzNcFaXPsBXJzkPiD3S',
  'artist_id': '648ZoUpTM6iIMTCgo3lLCE'},
 {'song_id': '5Nk4wgj4fmvue8sCs2kSlX',
  'song_name': 'FUNK DO BALKAN - Slowed',
  'duration_ms': 81336,
  'url': 'https://open.spotify.com/track/5Nk4wgj4fmvue8sCs2kSlX',
  'popularity': 63,
  'song_added': '2025-03-07T08:19:39Z',
  'album_id': '6PZBt4XZvd1ElHAHG31J1j',
  'artist_id': '60vF1fLR6yzLxCQUlnAYYj'},
 {'song_id': '28Qri8CIMxJUQauS8YOR7o',
  'song_name': 'Ela Vira Mortal',
  'duration_ms': 136370,
  'url': 'https://open.spotify.com/track/28Qri8CIMxJUQauS8YOR7o',
  'popularity': 60,
  'song_added': '2025-03-07T08:19:45Z',
  'album_id': '05EQpLFKhJ1m4YElm4zDHr',
  'artist_id': '1yTrrABG9Vr2Y9lbHupN3f'},
 {'song_id': '70FceppUZq9dQz1mDPcHcs',
  'song_name': 'Death Is No More',
  'duration_ms': 138500,
  'url': 'https://open.spotify.com/track/70FceppUZq9dQz1mDPcHcs',
  'popularity': 67,
  'song_added': '2025-03-07T08:37:35Z',
  'album_id': '5Ide1hRSwzUYUnTQhq6CBv',
  'artist_id': '4RsEAdLhbUy7j3zHWauPwF'},
 {'song_id': '0R902FnwJO8kBZYvtpQLrL',
  'song_name': 'YUM YUM',
  'duration_ms': 129697,
  'url': 'https://open.spotify.com/track/0R902FnwJO8kBZYvtpQLrL',
  'popularity': 63,
  'song_added': '2025-03-07T08:37:45Z',
  'album_id': '7Bc7xEWvkW01bvq5jAhCQS',
  'artist_id': '5IpS1TN1Crp8Ym4zjiIrtK'},
 {'song_id': '6kJjlOWBwnDwIBsvlwTNIF',
  'song_name': 'BAD PARENTING FUNK',
  'duration_ms': 87834,
  'url': 'https://open.spotify.com/track/6kJjlOWBwnDwIBsvlwTNIF',
  'popularity': 68,
  'song_added': '2025-03-07T08:37:49Z',
  'album_id': '2DNOGCn0szoh9f3rAnhF7b',
  'artist_id': '1iKfUld50BOVBIgHy3GlGt'},
 {'song_id': '1lS2qOUk6GA20XvjjrWc25',
  'song_name': 'MANDA BALA',
  'duration_ms': 100465,
  'url': 'https://open.spotify.com/track/1lS2qOUk6GA20XvjjrWc25',
  'popularity': 65,
  'song_added': '2025-03-07T08:38:02Z',
  'album_id': '4ibsk1iPM7xDpJkNXREmsl',
  'artist_id': '09cKncAQn28NqTUORLMwSR'},
 {'song_id': '2iRiWUoB7tNnG23KlM3Ui7',
  'song_name': 'RISADA CHUCK 01 - Super Slowed',
  'duration_ms': 130360,
  'url': 'https://open.spotify.com/track/2iRiWUoB7tNnG23KlM3Ui7',
  'popularity': 65,
  'song_added': '2025-03-07T08:38:27Z',
  'album_id': '7lolzbhq4moSJPfFpdosl5',
  'artist_id': '3uA4unR7LBOcqjpbOeCs0Y'},
 {'song_id': '0RgKtaVv27Nff2y29qaD8W',
  'song_name': 'ICEWHORE!',
  'duration_ms': 79052,
  'url': 'https://open.spotify.com/track/0RgKtaVv27Nff2y29qaD8W',
  'popularity': 61,
  'song_added': '2025-03-07T08:44:35Z',
  'album_id': '5J00ADHG1jlJiLjQDPURVh',
  'artist_id': '1TTHC3GlNDaE5eVoC3BVxm'},
 {'song_id': '6vEOZGTBgE6gASrzAWNxTH',
  'song_name': 'MONTAGEM DIAMANTE ROSA',
  'duration_ms': 99692,
  'url': 'https://open.spotify.com/track/6vEOZGTBgE6gASrzAWNxTH',
  'popularity': 60,
  'song_added': '2025-03-07T08:44:41Z',
  'album_id': '28N1pcdMLhrEajfJKkBkl1',
  'artist_id': '3yn6fs9MkW1i4V3S2G8Dxs'},
 {'song_id': '7yIwT8zSR8dzl0rWXbW2jm',
  'song_name': 'MTG - VINGANÇA',
  'duration_ms': 75692,
  'url': 'https://open.spotify.com/track/7yIwT8zSR8dzl0rWXbW2jm',
  'popularity': 58,
  'song_added': '2025-03-07T08:44:46Z',
  'album_id': '7DGsEVuwdKBKrzDx8fzEKn',
  'artist_id': '3QMpCp3GHiHXgnX1LldXWe'},
 {'song_id': '25MzUGleMnmyoeTNRZ8QF1',
  'song_name': 'VAPO NO SETOR',
  'duration_ms': 67596,
  'url': 'https://open.spotify.com/track/25MzUGleMnmyoeTNRZ8QF1',
  'popularity': 71,
  'song_added': '2025-03-07T08:44:52Z',
  'album_id': '6h4Lw0QisEuuAwmnMQvbse',
  'artist_id': '3wQNcarvRuzhz2Fg1pVDxZ'},
 {'song_id': '2SQp5yapF1ZwiuKgaFuFMJ',
  'song_name': 'Montagem Melodia Explosiva - Slowed',
  'duration_ms': 104347,
  'url': 'https://open.spotify.com/track/2SQp5yapF1ZwiuKgaFuFMJ',
  'popularity': 59,
  'song_added': '2025-03-07T08:53:20Z',
  'album_id': '3D2j7JQjj9Kjc8sOfikmV6',
  'artist_id': '1PvcWjADPMezv8CTyJO9Uk'},
 {'song_id': '5VZ0soW5syQfefCUj603DW',
  'song_name': 'MASHA ULTRAFUNK',
  'duration_ms': 93650,
  'url': 'https://open.spotify.com/track/5VZ0soW5syQfefCUj603DW',
  'popularity': 68,
  'song_added': '2025-03-18T19:45:04Z',
  'album_id': '43DSGSYCywacjEkdeSv4DC',
  'artist_id': '5Z56BMrvQB2rBAa5kffTPD'},
 {'song_id': '5WMrHMfkarliApsXvwUTrh',
  'song_name': 'z-beta 2 - Super Slowed',
  'duration_ms': 94040,
  'url': 'https://open.spotify.com/track/5WMrHMfkarliApsXvwUTrh',
  'popularity': 60,
  'song_added': '2025-03-24T23:41:07Z',
  'album_id': '6dRJ8zaG9oTGrwpfu0Itld',
  'artist_id': '32Pxa55IN0QAmFtzWcT2w9'},
 {'song_id': '5smCqaAEcKpArEBVhtaryT',
  'song_name': 'MY TYPE - Slowed',
  'duration_ms': 91585,
  'url': 'https://open.spotify.com/track/5smCqaAEcKpArEBVhtaryT',
  'popularity': 60,
  'song_added': '2025-04-05T04:13:26Z',
  'album_id': '4yUHDMHDEl6Th3jPimciMz',
  'artist_id': '4pmKpROq7rAVibM7qR9h6P'},
 {'song_id': '03E0f4JneWZEtrQPU6EsIV',
  'song_name': 'BLOODY! - ULTRA SLOWED',
  'duration_ms': 139384,
  'url': 'https://open.spotify.com/track/03E0f4JneWZEtrQPU6EsIV',
  'popularity': 67,
  'song_added': '2025-04-05T04:13:55Z',
  'album_id': '0yr5YRR7l813mmHITxmFWa',
  'artist_id': '1qaCszXlFNPEnCELYBixa5'},
 {'song_id': '7qvDmYmPjrIosceqmSriCa',
  'song_name': 'life force',
  'duration_ms': 109440,
  'url': 'https://open.spotify.com/track/7qvDmYmPjrIosceqmSriCa',
  'popularity': 73,
  'song_added': '2025-05-10T16:33:18Z',
  'album_id': '6OCivCvAUhsjgqn4EJXH87',
  'artist_id': '6T9oTkBolkKzQJ5ltR7Yr8'},
 {'song_id': '0cJwt3tpaMOXPAXkaHAp7k',
  'song_name': 'BOUNCE FUNK - Slowed',
  'duration_ms': 97368,
  'url': 'https://open.spotify.com/track/0cJwt3tpaMOXPAXkaHAp7k',
  'popularity': 64,
  'song_added': '2025-03-26T23:51:24Z',
  'album_id': '572YC1K4uc7PjFqb6xaICD',
  'artist_id': '0pSdNszQKrzI6m9okVVSL5'},
 {'song_id': '06PqeO7IInus2yvzsZwZhf',
  'song_name': 'CUTE DEPRESSED',
  'duration_ms': 96946,
  'url': 'https://open.spotify.com/track/06PqeO7IInus2yvzsZwZhf',
  'popularity': 72,
  'song_added': '2025-05-10T16:34:30Z',
  'album_id': '5qaY84OJqYT635rMGeWBzJ',
  'artist_id': '12Swjg82MNiUOfl1GB3XFx'},
 {'song_id': '48WnIIBbnttcwUQ77MBoMI',
  'song_name': 'MONTAGEM LADRAO',
  'duration_ms': 75240,

In [46]:
album_df =pd.DataFrame.from_dict(album_list)

In [47]:
album_df.head()

,album_id,name,release_date,total_tracks,album_url
0,6xUYw5goKIoyJQi9C27UBy,NUNCA MUDA?,2025-01-09,6,https://open.spotify.com/album/6xUYw5goKIoyJQi...
1,0I7096R74VFP2xnMmp33sY,PASSO BEM SOLTO,2024-04-23,5,https://open.spotify.com/album/0I7096R74VFP2xn...
2,4s7LxMlh6RxgdMhldfMe8u,Funk de Beleza,2024-10-04,3,https://open.spotify.com/album/4s7LxMlh6RxgdMh...
3,3bT53CJPMsSXSn0vDAX2Do,DIA DELÍCIA,2025-04-25,4,https://open.spotify.com/album/3bT53CJPMsSXSn0...
4,5fvUS8yHMCkTZj4sJ0FHDV,Vem Vem,2025-05-30,4,https://open.spotify.com/album/5fvUS8yHMCkTZj4...

In [64]:
album_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 78 entries, 0 to 78
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   album_id       78 non-null     object
 1   name           78 non-null     object
 2   release_date   78 non-null     datetime64[ns]
 3   total_tracks   78 non-null     int64
 4   album_url      78 non-null     object
 5   ;release_date  78 non-null     datetime64[ns]
dtypes: datetime64[ns](2), int64(1), object(3)
memory usage: 4.3+ KB

In [70]:
album_df['release_date'] =pd.to_datetime(album_df['release_date'])

C:\Users\Admin\AppData\Local\Temp\ipykernel_13644\91995963.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  album_df['release_date'] =pd.to_datetime(album_df['release_date'])

In [52]:
album_df=album_df.drop_duplicates(subset=['album_id'])

In [53]:
artists_df=pd.DataFrame.from_dict(artists_list)

In [55]:
artists_df = artists_df.drop_duplicates(subset=['artists_id'])

In [56]:
song_df = pd.DataFrame.from_dict(song_list)

In [58]:
song_df = song_df.drop_duplicates(subset=['song_id'])

In [59]:
song_df.head()

,song_id,song_name,duration_ms,url,popularity,song_added,album_id,artist_id
0,5EIjpM1B1VsLoKvv2iwd0P,NUNCA MUDA?,81500,https://open.spotify.com/track/5EIjpM1B1VsLoKv...,76,2025-03-07T07:49:17Z,6xUYw5goKIoyJQi9C27UBy,5dDNNq04RjKXFOADdHd6VX
1,4sTlQPMyoFMPdhAJvErBN3,PASSO BEM SOLTO - Slowed,116072,https://open.spotify.com/track/4sTlQPMyoFMPdhA...,85,2025-05-10T16:34:06Z,0I7096R74VFP2xnMmp33sY,5SCDfg1YoEfI5gFtXqEWah
2,43jExF2HeZ6cJIGrWF0ie4,Funk de Beleza - Slowed,145115,https://open.spotify.com/track/43jExF2HeZ6cJIG...,77,2025-03-07T07:49:21Z,4s7LxMlh6RxgdMhldfMe8u,3g0UoyvaTaHUrfpHiRqsD1
3,094IjHeVUviN4aBnSXYsuj,DIA DELÍCIA,75461,https://open.spotify.com/track/094IjHeVUviN4aB...,86,2025-07-09T07:59:30Z,3bT53CJPMsSXSn0vDAX2Do,1kd6WqngBvP0Vthu1sGI0j
4,2FnkrCrbXJuebXxnVtXiHI,Vem Vem,83183,https://open.spotify.com/track/2FnkrCrbXJuebXx...,83,2025-07-28T18:37:14Z,5fvUS8yHMCkTZj4sJ0FHDV,2q5vFLZus8uaVSzmIwH4Tz

In [71]:
song_df['song_added']= pd.to_datetime(song_df['song_added'])

In [72]:
song_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 79 entries, 0 to 78
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   song_id      79 non-null     object
 1   song_name    79 non-null     object
 2   duration_ms  79 non-null     int64
 3   url          79 non-null     object
 4   popularity   79 non-null     int64
 5   song_added   79 non-null     datetime64[ns, UTC]
 6   album_id     79 non-null     object
 7   artist_id    79 non-null     object
dtypes: datetime64[ns, UTC](1), int64(2), object(5)
memory usage: 5.1+ KB

In [77]:
album_df.loc[:, 'release_date'] = pd.to_datetime(album_df['release_date'])

In [79]:
album_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 78 entries, 0 to 78
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   album_id       78 non-null     object
 1   name           78 non-null     object
 2   release_date   78 non-null     datetime64[ns]
 3   total_tracks   78 non-null     int64
 4   album_url      78 non-null     object
 5   ;release_date  78 non-null     datetime64[ns]
dtypes: datetime64[ns](2), int64(1), object(3)
memory usage: 4.3+ KB